### ISSUE TITLE
Not possible to call mAPI methods (macro API) after stopping/aborting a macro (SF#9)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#10]
This was an internal ALBA ticket (RT#15866). I am moving it to the sardana tracker:

When I use debug/info logging from on_abort() method it throws this exception:

```Error in on_abort(): Traceback (most recent call last):                                                                                                                            
  File "/homelocal/sicilia/ds/python/macroserver/macro.py", line 1099, in _abortOnError                                                                                            
    self.on_abort()                                                                                                                                                                
  File "/homelocal/sicilia/local/Zibi/macros/icepap.py", line 276, in on_abort                                                                                                     
    self.debug('Aborting all motors.')                                                                                                                                             
  File "/homelocal/sicilia/ds/python/macroserver/macro.py", line 231, in new_fn                                                                                                    
    ret = fn(*args, **kwargs)                                                                                                                                                      
  File "/homelocal/sicilia/ds/python/macroserver/macro.py", line 398, in debug                                                                                                     
    return taurus.core.util.Logger.debug(self, *args, **kw)                                                                                                                        
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/util/log.py", line 626, in debug                                                                                   
    self.log_obj.debug(msg, *args, **kw)                                                                                                                                           
  File "/usr/lib/python2.6/logging/__init__.py", line 1009, in debug                                                                                                               
    self._log(DEBUG, msg, args, **kwargs)                                                                                                                                          
  File "/usr/lib/python2.6/logging/__init__.py", line 1129, in _log                                                                                                                
    self.handle(record)                                                                                                                                                            
  File "/usr/lib/python2.6/logging/__init__.py", line 1139, in handle                                                                                                              
    self.callHandlers(record)                                                                                                                                                      
  File "/usr/lib/python2.6/logging/__init__.py", line 1176, in callHandlers                                                                                                        
    hdlr.handle(record)                                                                                                                                                            
  File "/usr/lib/python2.6/logging/__init__.py", line 662, in handle                                                                                                               
    self.emit(record)                                                                                                                                                              
  File "/homelocal/sicilia/ds/python/macroserver/attributehandler.py", line 25, in emit                                                                                            
    self.sendText(output)                                                                                                                                                          
  File "/homelocal/sicilia/ds/python/macroserver/attributehandler.py", line 31, in sendText                                                                                        
    self._dev().push_change_event(self._attr_name, output)                                                                                                                         
DevFailed: DevFailed[                                                                                                                                                              
DevError[                                                                                                                                                                          
    desc = Not able to acquire serialization (dev, class or process) monitor                                                                                                       
  origin = TangoMonitor::get_monitor                                                                                                                                               
  reason = API_CommandTimedOut                                                                                                                                                     
severity = ERR]                                                                                                                                                                    
]       
```
when I remove logging from on_abort it works well.

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/9](https://sourceforge.net/p/sardana/tickets/9)

**Comment by reszelaz** [comment]
I just asked @tiagocoutinho if it was a design decision to not allow calls to the `mAPI` (macro API) methods (including executing other macros) after stopping/aborting or if we could consider it as a bug. He does not remember it to be a design decision and it must be a bug! @tiagocoutinho, many thanks for your help here!

We could try fixing it but I would postpone it until after the release. I'm adding it to the Jul20 milestone.
