### ISSUE TITLE
when gets a pseudo counter's calc method called?

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1011]
when I understand my door output correctly, a pseudo counter's calc method for each output_role is called whenever any input_role has changed. Is that correct?

if yes, is it possible to call the calc method only once when all input_roles are done with acquisition?

**Comment by dschick** [comment]
I ask that also because of the following error/bug I just found:

when I have a pseudo counter with a lot of inputs and outputs, lets say each 30, then I am getting the following error in the Door output, but only during scans, not for a single `ct`

```
SardanaTP.W009 DEBUG    2019-01-11 11:27:21,344 xmcd.Acquisition.Synchronization: <- action_loop
SardanaTP.W008 ERROR    2019-01-11 11:27:21,796 SardanaTP.SardanaTP.W008: Uncaught exception running job 'run' called from thread SardanaTP.W010:
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/xmcd/Repos/sardana/src/sardana/util/funcgenerator.py", line 194, in run
    self.fire_active()
  File "/home/xmcd/Repos/sardana/src/sardana/util/funcgenerator.py", line 259, in fire_active
    self.fire_event(EventType("active"), self._id)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanaevent.py", line 130, in _fire_event
    real_listener.event_received(self, event_type, event_value)
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolacquisition.py", line 348, in event_received
    **self._0d_acq_args.kwargs)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolaction.py", line 346, in run
    self.action_loop()
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolacquisition.py", line 1230, in action_loop
    element.append_value_buffer(value, self._index, propagate=2)
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolbasechannel.py", line 271, in append_value_buffer
    val_buffer.append(value, idx)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanabuffer.py", line 158, in append
    self.fire_add_event()
  File "/home/xmcd/Repos/sardana/src/sardana/sardanabuffer.py", line 206, in fire_add_event
    self.fire_event(evt_type, self.last_chunk)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolpseudocounter.py", line 64, in on_change
    self.remove_physical_values(idx)
  File "/home/xmcd/Repos/sardana/src/sardana/pool/poolpseudocounter.py", line 76, in remove_physical_values
    value_buf.remove(idx)
  File "/home/xmcd/Repos/sardana/src/sardana/sardanabuffer.py", line 195, in remove
    raise KeyError(msg)
KeyError: 'value with %s index is not in buffer'
```

I just got rid of that, by using 30 pseudo counter controllers with one input and one output each, however, the error message might be worth noting here.

**Comment by reszelaz** [comment]
Sorry I missed this issue yesterday..

> when I understand my door output correctly, a pseudo counter's calc method for each output_role is called whenever any input_role has changed. Is that correct?

I would say so. Since the counter/timers are read **during** the acquisition this means quite some `calc` method calls. For 1D and 2D you should have only one call for each final read. Is it what you observe?

> if yes, is it possible to call the calc method only once when all input_roles are done with acquisition?

Both, in case of the step and continuous scans, the value reported to the scan records are calculated from the input values read when the given acquisition point is done so the record values should be correct. I'm affraid that there is no way to avoid the pseudo counter's (based on counter/timers) calculation during the acquisition. Maybe you could _cheat_ by returning `None` or raising an exception in the controller while acquiring or something like that, but I've never tried it - these are just guesses. We have in mind optimizing these calls, or allowing to the user to disable them, but it was not set as priority up to now.

> when I have a pseudo counter with a lot of inputs and outputs, lets say each 30, then I am getting the following error in the Door output, but only during scans, not for a single ct

Certainly it is worth investigation. I see that you are using a 0D in this acuqisiiton, is it right?

Do you know if it is possible to reproduce it with with dummy controllers and `IoverI0`?
If it's not possible to reproduce it with dummies it would be cerainly of help if you could provide a pseudo controller code to reproduce it.

**Comment by dschick** [comment]
Hej @reszelaz ,

thanks for the reply. This issue is linked to #1010 as I am calculating the pseudo counter value depending on a motor position. Having multiple calc calls during an acquisition as well as direkt hardware calls of the motor (#1010) was slowing down my configuration a lot.

The final result of the pseudo counter was always correct, as you mentioned.

I will try to reproduce the error messages with dummy controllers as soon as possible.

The pseudo counter controller can be found here: https://github.com/dschick/sardanaControllers/blob/xmcd/pseudoCounterAltOn.py

**Comment by reszelaz** [comment]
@dschick the pseudo counters exceptions that you were seeing on the Pool's output should be fixed in the develop branch. Thanks for the report!
