### ISSUE TITLE
Invalid module h5storage when running macroserver

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#1018]
When running macroserver in origin/qt5 branch, an error is reported when loading h5storage module, related with h5py and future modules. Using h5py 2.7.1 and future 0.15.2.

Error in macroserver logs, when executing it with --log-level=debug:

<pre>
MainThread     INFO     2019-01-21 11:52:35,253 ModuleManager: (re)loading module h5storage...
MainThread     ERROR    2019-01-21 11:52:35,277 ModuleManager: Invalid module h5storage
MainThread     DEBUG    2019-01-21 11:52:35,277 ModuleManager: Details:
Traceback (most recent call last):
  File "/home/mrosanes/PycharmProjects/sardana/src/sardana/sardanamodulemanager.py", line 194, in isValidModule
    m = imp.load_module(fake_name, mfile, pathname, desc)
  File "/home/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/recorders/h5storage.py", line 39, in <module>
    import h5py
  File "/usr/local/lib/python2.7/dist-packages/h5py/__init__.py", line 62, in <module>
    from .tests import run_tests
  File "/usr/local/lib/python2.7/dist-packages/h5py/tests/__init__.py", line 15, in <module>
    from . import old, hl
  File "/usr/local/lib/python2.7/dist-packages/h5py/tests/old/__init__.py", line 4, in <module>
    from . import ( test_attrs,
  File "/usr/local/lib/python2.7/dist-packages/h5py/tests/old/test_group.py", line 41, in <module>
    filename_encode(u"��")
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/compat.py", line 116, in filename_encode
    return fsencode(filename)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/compat.py", line 70, in fsencode
    return filename.encode(encoding, errors)
  File "/usr/lib/python2.7/dist-packages/future/utils/surrogateescape.py", line 59, in surrogateescape_handler
    decoded = replace_surrogate_encode(mystring)
  File "/usr/lib/python2.7/dist-packages/future/utils/surrogateescape.py", line 86, in replace_surrogate_encode
    raise exc
NameError: global name 'exc' is not defined
</pre>

**Comment by mrosanes** [comment]
Indeed, setting the LANG to en_US.UTF-8 solves this issue. I close this issue as it was already reported on Taurus
Thanks

**Comment by reszelaz** [comment]
BTW the latest reszelaz/sardana-test docker image should have this variable already set.
