### ISSUE TITLE
trend window not opening

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1037]
after the recent update to the development branch I also get this error when trying to open the trend window from the expconf:
```

Traceback (most recent call last):
  File "/home/xmcd/Repos/sardana/src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py", line 689, in onPlotsButtonToggled
    from sardana.taurus.qt.qtgui.macrolistener import \
  File "/home/xmcd/Repos/sardana/src/sardana/taurus/qt/qtgui/macrolistener/__init__.py", line 31, in <module>
    from .macrolistener import *  # noqa: F401,F403
  File "/home/xmcd/Repos/sardana/src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py", line 40, in <module>
    from builtins import object
ImportError: No module named builtins

```

**Comment by cpascual** [comment]
Hi, this is fixed installing the `future` python module.
(e.g. in debian, `apt-get install python-future`)

Taurus already depends on it (so if you (re)install the latest develop branch of taurus with pip, it should be installed. And since sardana depends on taurus>=4.5, this should also be taken care of.

I close this. Feel free to reopen if it didn't help.
