### ISSUE TITLE
timescan doesn't work if any general hook is activated

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1064]
If any general hook is defined the macro timescan does not work.
How to reproduce it:

- define a general hook, ex.
Door_indepacq_1 [3]: defgh ct pre-scan

- run timescan:
Door_indepacq_1 [4]: timescan 10 1 0.1
Error: argument of type 'NoneType' is not iterable

Hier the print out with debug on:
Error details:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 1466, in __runXMLMacro
    macro_obj, _ = self._prepareXMLMacro(xml)
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 1169, in _prepareXMLMacro
    self._prepareGeneralHooks(macro_obj)
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 1154, in _prepareGeneralHooks
    macro_obj.appendHook((hook, hook_places))
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macro.py", line 223, in appendHook
    if hint in allowed_hookhints:
TypeError: argument of type 'NoneType' is not iterable
Job ended (stopped=False, aborted=False)

**Comment by teresanunez** [comment]
It is related to our installed version, sorry.
