### ISSUE TITLE
macroexecutor does not show popups from 'raise ValueError'

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#1079]
macroexecutor does not show popups from 'raise ValueError'
Tested on  sardana v2.7.1-alpha

It can be tested by loading the following macro in macroexecutor and by giving the value 1 to the input parameter 'n_int'.

<pre>
from sardana.macroserver.macro import Macro, Type

class popup(Macro):

    param_def = [['n_int', Type.Integer, 1, 'input int']]

    def run(self, n_int):
        msg = "popup error"
        if n_int == 1:
            raise ValueError(msg)
        else:
            print("hiho")
</pre>

The error shown in macroserver is:

<pre>
Traceback (most recent call last):
  File "/home/mrosanes/PycharmProjects/sardana/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 1010, in onMacroStatusUpdated
    MacroRunException, exc_value, exc_stack)
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/dialog/taurusmessagebox.py", line 81, in __init__
    self, designMode)
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 280, in __init__
    self.setError(*self._exc_info)
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 482, in setError
    handler_klass(self)
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 62, in __init__
    self.setError(*msgbox.getError())
  File "/home/mrosanes/PycharmProjects/sardana/src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py", line 256, in setError
    html = html_orig.format(style=style)
KeyError: '\n        style'
</pre>

**Comment by mrosanes** [comment]
Note: On Sardana 2.6.1 the macroexecutor popup was working correctly.

**Comment by mrosanes** [comment]
Commit 2db2876 was introducing this bug.
Pull request https://github.com/sardana-org/sardana/pull/1088 proposes a fix.
