### ISSUE TITLE
module object has no PY_OBJECT

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1168]
Buenos,

when I start spock with the latest Sardana 2.8 release I get the follow error:

```
Dummy-47       ERROR    2019-07-04 11:25:10,547 root: Invalid alias: The name mv can't be aliased because it is another magic command.
MainThread     INFO     2019-07-04 11:25:52,199 TaurusRootLogger: Using PyQt4 (v4.12.1 , with Qt 4.8.7)
MainThread     INFO     2019-07-04 11:25:52,270 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/usr/local/bin/spock", line 11, in <module>
    load_entry_point('sardana', 'console_scripts', 'spock')()
  File "/home/xmcd/Repos/sardana/src/sardana/spock/__init__.py", line 34, in main
    run()
  File "/home/xmcd/Repos/sardana/src/sardana/spock/ipython_01_00/genutils.py", line 1370, in run
    prepare_input_handler()
  File "/home/xmcd/Repos/sardana/src/sardana/spock/ipython_01_00/genutils.py", line 1271, in prepare_input_handler
    import sardana.spock.inputhandler
  File "/home/xmcd/Repos/sardana/src/sardana/spock/inputhandler.py", line 72, in <module>
    class MessageHandler(Qt.QObject):
  File "/home/xmcd/Repos/sardana/src/sardana/spock/inputhandler.py", line 74, in MessageHandler
    messageArrived = Qt.pyqtSignal(compat.PY_OBJECT)
AttributeError: 'module' object has no attribute 'PY_OBJECT'
```

**Comment by teresanunez** [comment]
Hi @dschick, I can not reproduce the problem. In which OS and which version of Taurus do you have?.

**Comment by reszelaz** [comment]
I think you either need to use the 2.8.0 release (from tag) or the latest sardana develop branch with the latest taurus develop branch. Please confirm that this helps. Thanks a lot!

**Comment by dschick** [comment]
thanks, it works with latest taurus release.
Maybe one can somehow check the version during startup?
I did a `pip install --upgrade taurus` but obviously this just brought be the latest stable release.

**Comment by reszelaz** [comment]
I agree, the sardana develop `setup.py` should require that.
