### ISSUE TITLE
ct 1 fails after continuous scan

### ISSUE THREAD

**Issue by julianofjm** [sardana-org/sardana#1171]
Hi all,

We are trying sardana 2.8 and I found an issue that I managed to reproduce using sar_demo elements. Please let me know if you can reproduce it. If necessary I can provide more details.

- with a totally fresh sardana instance (Pool and MacroServer) run sar_demo. 
- create a new measurement group ("mntgrp01-fly", for example) with tg01 (triggergate controller) in the "Synchronizer" column. Apply it.
- launch a fly-scan, for example: "ascanct mot01 1 2 10 0.1 0.1". It will execute the continuous scan with success.
- try "ct 1" with the original measurement group ("mntgrp01").

Pool will hang and keep throwing an error as the following:

`EventTH.W001   ERROR    2019-07-15 22:22:18,928 EventTH.EventTH.W001: Uncaught exception running job 'set_attribute_push' called from thread SardanaTP.W009:
  File "/usr/lib64/python2.7/threading.py", line 785, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/taurus/core/util/threadpool.py", line 142, in run
    cmd(*args, **kw)
  File "/usr/lib/python2.7/site-packages/sardana/pool/poolaction.py", line 346, in run
    self.action_loop()
  File "/usr/lib/python2.7/site-packages/taurus/core/util/log.py", line 196, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sardana/pool/poolacquisition.py", line 1124, in action_loop
    acquirable.put_value(value)
  File "/usr/lib/python2.7/site-packages/sardana/pool/poolbasechannel.py", line 257, in put_value
    val_attr.set_value(value, propagate=propagate)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaattribute.py", line 127, in set_value
    propagate=propagate)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaattribute.py", line 136, in _set_value
    self.fire_read_event(propagate=propagate)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaattribute.py", line 285, in fire_read_event
    self.fire_event(evt_type, self)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/usr/lib/python2.7/site-packages/sardana/pool/poolbasechannel.py", line 212, in on_change
    self.fire_event(evt_type, evt_value)
  File "/usr/lib/python2.7/site-packages/sardana/sardanabase.py", line 131, in fire_event
    listeners=listeners)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/usr/lib/python2.7/site-packages/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/usr/lib/python2.7/site-packages/sardana/tango/pool/CTExpChannel.py", line 94, in on_ct_changed
    self._on_ct_changed(event_source, event_type, event_value)
  File "/usr/lib/python2.7/site-packages/sardana/tango/pool/CTExpChannel.py", line 147, in _on_ct_changed
    priority=priority, error=error, synch=False)
  File "/usr/lib/python2.7/site-packages/sardana/tango/core/SardanaDevice.py", line 317, in set_attribute
    priority=priority, synch=synch)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/taurus/core/util/threadpool.py", line 142, in run
    cmd(*args, **kw)
  File "/usr/lib/python2.7/site-packages/sardana/tango/core/SardanaDevice.py", line 329, in set_attribute_push
    error=error, priority=priority)
  File "/usr/lib/python2.7/site-packages/sardana/tango/core/SardanaDevice.py", line 426, in _set_attribute_push
    self.push_change_event(*args)
TypeError: Expecting a numeric type, but it is not. If you use a numpy type instead of python core types, then it must exactly match (ex: numpy.int32 for PyTango.DevLong)`

Cheers,
Juliano

**Comment by cmft** [comment]
Hola @julianofjm,
I trying to reproduce your error (using the same version of Sardana) and i'm not able to do it. Which version of Tango, (Py)Tango, and Taurus do you have installed?

I used:
```
 Tango= 9.2.5
 PyTango=9.2.5a
Taurus = 4.5.4-alpha
```

**Comment by julianofjm** [comment]
Hola @cmft ,
Thanks for the reply.
I am using the following versions:
- Tango = 9.2.5
- PyTango = 9.2.3
- Taurus = 4.5.1

I suspect that could be the taurus version, since one of the lines in the error appoints to .py file from taurus.
The latest release of taurus is 4.5.1, correct? 
This version 4.5.4-alpha is from develop branch? I will try to use it.

**Comment by julianofjm** [comment]
Hi,

I could reproduce it with taurus 4.5.4-alpha. It didn't happen at the first attempt but after few continuous scan using mntgrp01-fly followed by "ct 1 mntgrp01" command the issue appeared again.

With the previous setup (sardana 2.8 and taurus 4.5.1) I got the same result using measurement groups with Alba electrometers (one for step scan and other for fly-scan). I noted that when perform ct 1 the equipment doesn't change back to "Software" acquisition mode, what could be one of the explanation for the event error, since the equipment itself is waiting for hardware triggers, even doing a ct 1 of a software synchronized measurement group. Only restarting the Pool recovers the system.

**Comment by reszelaz** [comment]
I just quickly reviewed the code and I have an idea. Could you please try to remove the condition from line 442 from `sardana.pool.poolacquisition` and always apply the configuration regardless if it was changed or not? I think this condition does not take into account that someone was changing the active measurement group.

**Comment by julianofjm** [comment]
Hi @reszelaz,
Removing the condition it works fine with sar_demo elements. I've tested several fly-scans followed by "ct 1 mntgrp01" and all of them works.
Could we just remove this condition? Is it not important in any other case?

I tried the same with the electrometer and the acquisition itself worked as well, it switches automatically between software and hardware mode, but when in software mode (ct 1), the same error appears in the Pool terminal. It's kept in a loop for while between launch the command and the acquisition starting. Although the error, the acquisition finishes fine.

Thanks a lot for the help,
Juliano

**Comment by amilan** [comment]
Hi @julianofjm, 
Together with @reszelaz we have been investigating this issue and seems to be related with the EM controller it self.

The ReadOne method of the controller that we are using in MAXIV is returning an empty list when the new data received is of length 0. That was causing the error.
The good news is that this issue was already fixed in the upstream repository (3rd party repository), the bad news is that we need to merge it with the version that we have in MAXIV.

Could you give a try to the version in the 3rd party repository and check if you still have the issue?
(https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/countertimer/Albaem2CoTiCtrl.py)

Thanks in advance.

**Comment by julianofjm** [comment]
Hi @amilan,

Precisely, I've changed ReadOne method in the controller and the error does not appear any more.
Everything solved!
Thanks a lot.
