### ISSUE TITLE
test_stop_meas_cont_acquisition_3 test randomly fails on travis-ci

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1188]
This can be observed in this [build](https://travis-ci.com/reszelaz/sardana/jobs/230121128).

```console
======================================================================
FAIL: test_stop_meas_cont_acquisition_3 (sardana.tango.pool.test.test_measurementgroup.TangoAcquisitionTestCase)
Stop of the synchronized acquisition with two channels from the same controller using hardware trigger
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sardana-3.0.0a0-py3.5.egg/sardana/tango/pool/test/test_measurementgroup.py", line 253, in stop_meas_cont_acquisition
    self.assertEqual(state, desired_state, msg)
AssertionError: tango._tango.DevState.FAULT != tango._tango.DevState.ON : channel tango://sardana-test:10000/expchan/_test_ct_ctrl_1/1 state after stop is FAULT (should be ON)
----------------------------------------------------------------------
Ran 307 tests in 833.453s
```

**Comment by reszelaz** [comment]
I'm forced to reopen it. It still fails..
Anyone know an easy way to either to upload a log file as artifact or eventually increase the job output limit in order to cat the log file there?
