### ISSUE TITLE
Crash on spock startup on buster (matplotlib?)

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1209]
To reproduce you can use [this VM](https://filesender.rediris.es/?s=download&token=b1ef4d3b-b77f-9b62-8e13-909b0f403d39). It has all the Sardana and Taurus dependencies installed according to this [vagrant configuration](https://github.com/sardana-org/sardana-training/blob/master/vagrant/provision.sh). You will need to install Taurus and Sardana on it, for example using:
```
pip3 install --user <url>
```

Then first start `Sardana demo1` server and then start spock:

```
vagrant@buster:~/sardana-training$ spock
MainThread     INFO     2019-10-02 17:09:44,175 TaurusRootLogger: Using PyQt5 (v5.11.3 with Qt 5.11.3 and Python 3.7.3)
Profile 'spockdoor' does not exist. Do you want to create one now ([y]/n)? malloc_consolidate(): invalid chunk size
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python3.7 path = /usr/bin pid = 1734
KCrash: Arguments: 
y
Available Door devices from buster.localdomain:10000 :
Door_demo1_1 (a.k.a. Door/demo1/1) (running)
Door name from the list? Door_demo1_1
Storing ipython_config.py in /home/vagrant/.ipython/profile_spockdoor... [DONE]
Spock 3.0.2-alpha -- An interactive laboratory application.

help      -> Spock's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: spockdoor

Connected to Door_demo1_1
MainThread     INFO     2019-10-02 17:10:33,918 matplotlib.font_manager: Could not open font file /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
```

here it hangs, and after Ctrl+C:

```
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1356, in <module>
    fontManager = json_load(_fmcache)
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 891, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/.cache/matplotlib/fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.local/bin/spock", line 10, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python3.7/site-packages/sardana/spock/__init__.py", line 34, in main
    run()
  File "/home/vagrant/.local/lib/python3.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 1377, in run
    launch_new_instance()
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 320, in initialize
    self.init_gui_pylab()
  File "/usr/lib/python3/dist-packages/IPython/core/shellapp.py", line 213, in init_gui_pylab
    r = enable(key)
  File "/usr/lib/python3/dist-packages/IPython/core/shellapp.py", line 200, in <lambda>
    enable = lambda key: shell.enable_pylab(key, import_all=self.pylab_import_all)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3005, in enable_pylab
    gui, backend = self.enable_matplotlib(gui)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2966, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/usr/lib/python3/dist-packages/IPython/core/pylabtools.py", line 314, in activate_matplotlib
    import matplotlib.pyplot
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.contour as contour
  File "/usr/lib/python3/dist-packages/matplotlib/contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1366, in <module>
    _rebuild()
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1347, in _rebuild
    fontManager = FontManager()
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 986, in __init__
    self.ttflist = createFontList(ttffiles)
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 497, in createFontList
    font = ft2font.FT2Font(fpath)
KeyboardInterrupt

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

After starting again it always report a crash (KCrash) but does not hang and the spock usable.

Anyone willing to investigate? It affects the ICALEPCS demo.

**Comment by tiagocoutinho** [comment]
Hi @reszelaz,

I can have a look

**Comment by tiagocoutinho** [comment]
Seems to be a bug with PyQt5 (see [here](https://github.com/openstenoproject/plover/issues/1042))

I can reproduce it with a simple python application:
```python
from PyQt5.QtWidgets import QApplication, QLabel
app = QApplication([])
label = QLabel('Hello World!')
label.show()
app.exec_()
```

Installing PyQt5 with `pip3 install --user PyQt5` seems to fix the problem.

Would that be good enough for you?

**Comment by reszelaz** [comment]
Thanks for looking into this. So the same issue that we have observed earlier with silx?
Do you know who is calling the QApplication with empty list of args in the case of Spock?
To know if it is a workaround for the Icalepcs demo i would need to repeat all the tests with Pyqt from pip, and also think on how to update it on the VM which was already redistributed to the participants. Do you think there is another chance to workaround this problem?

**Comment by tiagocoutinho** [comment]
Actually the problem comes from within spock

in sardana.spock.inputhandler (line 151):

```python
    def run(self, conn):
        # child process
        self._conn = conn
        app = Qt.QApplication.instance()
        if app is None:
            app = Qt.QApplication([])
        app.setQuitOnLastWindowClosed(False)
        self._msg_handler = MessageHandler(conn)
        TaurusManager().addJob(self.run_forever, None)
        app.exec_()
        conn.close()
        print("Quit input handler")
```

Replacing 
```python
app = Qt.QApplication([])
```
with:
```python
app = Qt.QApplication(['spock'])
```
seems to solve the problem.

I will make a PR

**Comment by reszelaz** [comment]
Great news! Thanks!
