### ISSUE TITLE
fscan not working

### ISSUE THREAD

**Issue by amilan** [sardana-org/sardana#1218]
Hi,

I have found an issue when trying to run an fscan macro.

If I run:

```
fscan "x=[5.]" 0.1 mot53 x*2
```

It works fine. But as soon as I add more elements in the X list it doesn't work.
For example:

```
fscan "x=[1, 2]" 1 mot53 x*2
```

doesn't work. It fails with the following error:

```
Door_amilan_2_1 [30]: www
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/msmacromanager.py", line 1561, in runMacro
    for step in macro_obj.exec_():
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/macro.py", line 2334, in exec_
    for i in it:
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/macros/scan.py", line 956, in run
    for step in self._gScan.step_scan():
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/scan/gscan.py", line 996, in step_scan
    for i in self.scan_loop():
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/scan/gscan.py", line 1057, in scan_loop
    self.measurement_group.putIntegrationTime(integ_time)
  File "/usr/lib/python2.7/site-packages/sardana/taurus/core/tango/sardana/pool.py", line 1709, in putIntegrationTime
    if self._last_integ_time == ctime:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Any idea or solution?

Regards.

**Comment by reszelaz** [comment]
Fixed in #1220.
