### ISSUE TITLE
sardanatestsuite migration to 3.0

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1249]
Hi,

I am currently trying to migrate Sardana to version 3.0 in a new setup.
However, I am struggleing a bit.

I installed tango 9.25 together with pytango 9.25 without problems.

Then I installed the latest taurus version from the development branch, resulting in multiple errors when doing the taurus testsuite, see https://github.com/taurus-org/taurus/issues/1036

However, I could install and run Sardana 3.0, but there are still many errors when running the sardanatestsuite:

```
sardanatestsuite 
MainThread     WARNING  2019-12-10 14:16:50,926 TaurusRootLogger: <frozen importlib._bootstrap>:219: DeprecationWarning: taurus.external.unittest is deprecated since 4.3.2. Use unittest instead

MainThread     WARNING  2019-12-10 14:16:50,927 TaurusRootLogger: <frozen importlib._bootstrap>:219: DeprecationWarning: taurus.external.argparse is deprecated since 4.3.2. Use argparse instead

MainThread     WARNING  2019-12-10 14:16:51,024 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     WARNING  2019-12-10 14:16:51,024 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     WARNING  2019-12-10 14:16:51,082 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     WARNING  2019-12-10 14:16:51,085 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     WARNING  2019-12-10 14:16:51,086 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     WARNING  2019-12-10 14:16:51,087 TaurusRootLogger: The door door/demo1/1 is not running. Ignore this message if you are building the documentation.
MainThread     INFO     2019-12-10 14:16:51,119 ModuleManager: (re)loading module basetypes...
MainThread     INFO     2019-12-10 14:16:51,121 ModuleManager: (re)loading module basetypes...
MainThread     INFO     2019-12-10 14:16:51,315 TaurusRootLogger: Using PyQt4 (v4.12.1 with Qt 4.8.7 and Python 3.6.9)
MainThread     INFO     2019-12-10 14:16:51,335 ModuleManager: (re)loading module basetypes...
MainThread     INFO     2019-12-10 14:16:51,337 ModuleManager: (re)loading module basetypes...
MainThread     INFO     2019-12-10 14:16:51,412 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
MainThread     WARNING  2019-12-10 14:16:51,422 TaurusRootLogger: <frozen importlib._bootstrap>:219: DeprecationWarning: taurus.core.util.argparse is deprecated since 4.5.4. Use argparse or (better) click instead

test_ct_macro_runs (sardana.macroserver.macros.test.test_ct.CtTest)
Testing ct with macro_runs(macro_name='ct', macro_params=['.3'], wait_timeout=2.5) ... ERROR
test_ct_macro_runs_2 (sardana.macroserver.macros.test.test_ct.CtTest)
Testing ct with macro_runs(macro_name='ct', macro_params=['.1'], wait_timeout=2.5) ... ERROR
test_ct_macro_stops (sardana.macroserver.macros.test.test_ct.CtTest)
Testing ct with macro_stops(macro_name='ct', macro_params=['1'], stop_delay=0.1, wait_timeout=3.5) ... ERROR
test_dumpenv_macro_runs (sardana.macroserver.macros.test.test_env.DumpenvTest)
Testing dumpenv with macro_runs() ... ERROR
test_lsenv_macro_runs (sardana.macroserver.macros.test.test_env.LsenvTest)
Testing lsenv with macro_runs(macro_params=['ascan', 'dscan']) ... ERROR
test_lsenv_macro_runs_2 (sardana.macroserver.macros.test.test_env.LsenvTest)
Testing lsenv with macro_runs(macro_params=['ascan']) ... ERROR
test_lsenv_macro_runs_3 (sardana.macroserver.macros.test.test_env.LsenvTest)
Testing lsenv with macro_runs() ... ERROR
test_lsvo_macro_runs (sardana.macroserver.macros.test.test_env.LsvoTest)
Testing lsvo with macro_runs() ... ERROR
test_senv_macro_runs (sardana.macroserver.macros.test.test_env.SenvTest)
Testing senv with macro_runs(macro_params=['MyEnvVar', 'test.dat']) ... ERROR
test_setvo_macro_runs (sardana.macroserver.macros.test.test_env.SetvoTest)
Testing setvo with macro_runs(macro_params=['PosFormat', '3']) ... ERROR
test_usenv_macro_runs (sardana.macroserver.macros.test.test_env.UsenvTest)
Testing usenv with macro_runs(macro_params=['MyEnvVar']) ... ERROR
test_usetvo_macro_runs (sardana.macroserver.macros.test.test_env.UsetvoTest)
Testing usetvo with macro_runs(macro_params=['PosFormat']) ... ERROR
test_expert (sardana.macroserver.macros.test.test_expert.ExpertTest) ... ERROR
test_prdef_macro_runs (sardana.macroserver.macros.test.test_expert.MacroTest)
Testing prdef with macro_runs(macro_name='prdef', macro_params=['wa'], wait_timeout=1) ... ERROR
test_relmac_macro_runs (sardana.macroserver.macros.test.test_expert.MacroTest)
Testing relmac with macro_runs(macro_name='relmac', macro_params=['wa'], wait_timeout=1) ... ERROR
test_relmaclib_macro_runs (sardana.macroserver.macros.test.test_expert.MacroTest)
Testing relmaclib with macro_runs(macro_name='relmaclib', macro_params=['standard'], wait_timeout=1) ... ERROR
test_meas (sardana.macroserver.macros.test.test_expert.MeasTest) ... skipped 'skip test until issue #57 is fixed'
test_sar_info_macro_runs (sardana.macroserver.macros.test.test_expert.SarinfoTest)
Testing sar_info with macro_runs(macro_params=['element_not_defined'], wait_timeout=1) ... ERROR
test_sar_info_macro_runs_2 (sardana.macroserver.macros.test.test_expert.SarinfoTest)
Testing sar_info with macro_runs(macro_params=['element_not_defined'], wait_timeout=1) ... ERROR
test_sar_info_macro_runs_3 (sardana.macroserver.macros.test.test_expert.SarinfoTest)
Testing sar_info with macro_runs(macro_params=['wa'], wait_timeout=1) ... ERROR
test_defgh_macro_runs (sardana.macroserver.macros.test.test_gh.GeneralHooksMacrosTest)
Testing defgh with macro_runs(macro_name='defgh', macro_params=['lsm mot.*', 'pre-acq'], wait_timeout=1) ... ERROR
test_defgh_macro_runs_2 (sardana.macroserver.macros.test.test_gh.GeneralHooksMacrosTest)
Testing defgh with macro_runs(macro_name='defgh', macro_params=['lsm', 'pre-acq'], wait_timeout=1) ... ERROR
test_lsgh_macro_runs (sardana.macroserver.macros.test.test_gh.GeneralHooksMacrosTest)
Testing lsgh with macro_runs(macro_name='lsgh', wait_timeout=1) ... ERROR
test_udefgh_macro_runs (sardana.macroserver.macros.test.test_gh.GeneralHooksMacrosTest)
Testing udefgh with macro_runs(macro_name='udefgh', wait_timeout=1) ... ERROR
test_gh (sardana.macroserver.macros.test.test_gh.GeneralHooksTest) ... MainThread     INFO     2019-12-10 14:16:51,996 Starter: Starting server Pool/unittest1_1...
MainThread     INFO     2019-12-10 14:16:53,021 Starter: Server Pool/unittest1_1 has been started
MainThread     INFO     2019-12-10 14:16:54,160 Starter: Starting server MacroServer/unittest1_1...
MainThread     INFO     2019-12-10 14:16:55,171 Starter: Server MacroServer/unittest1_1 has been started
MainThread     WARNING  2019-12-10 14:17:00,690 TaurusRootLogger: Model name "ampere.sxr.lab:10000/expchan/_test_ct_ctrl_1/1" is supported but not strictly valid. 
It is STRONGLY recommended that you change it to 
strictly follow tango scheme syntax
MainThread     WARNING  2019-12-10 14:17:00,729 TaurusRootLogger: Model name "ampere.sxr.lab:10000/expchan/_test_ct_ctrl_1/2" is supported but not strictly valid. 
It is STRONGLY recommended that you change it to 
strictly follow tango scheme syntax
MainThread     WARNING  2019-12-10 14:17:00,735 TaurusRootLogger: Model name "ampere.sxr.lab:10000/controller/dummycountertimercontroller/_test_ct_ctrl_1" is supported but not strictly valid. 
It is STRONGLY recommended that you change it to 
strictly follow tango scheme syntax
^CTraceback (most recent call last):
  File "/home/labuser/.local/bin/sardanatestsuite", line 11, in <module>
    load_entry_point('sardana', 'console_scripts', 'sardanatestsuite')()
  File "/home/labuser/Repos/sardana/src/sardana/test/testsuite.py", line 114, in main
    ret = run(exclude_pattern=args.exclude_pattern)
  File "/home/labuser/Repos/sardana/src/sardana/test/testsuite.py", line 87, in run
    result = runner.run(suite)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/labuser/Repos/sardana/src/sardana/macroserver/macros/test/test_gh.py", line 61, in test_gh
    self.create_meas(mg_config4)
  File "/home/labuser/Repos/sardana/src/sardana/macroserver/macros/test/test_gh.py", line 56, in create_meas
    sync=True, timeout=1.)
  File "/home/labuser/Repos/sardana/src/sardana/macroserver/macros/test/macroexecutor.py", line 91, in run
    self.wait(timeout)
  File "/home/labuser/Repos/sardana/src/sardana/macroserver/macros/test/macroexecutor.py", line 115, in wait
    self._wait(timeout)
  File "/home/labuser/Repos/sardana/src/sardana/tango/macroserver/test/macroexecutor.py", line 163, in _wait
    self._done_event.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

```

I have the feeling that these issues might be related to some routing issues, since I have the tangoDB and Sardana running on the same host, which itself is connected to two different networks.

If I install the latest Python2 versions of Taurus + Sardana, there are no errors at all.

Best

Daniel

**Comment by reszelaz** [comment]
Currently the `sardanatestsuite` requires to manually setup the test infrastructure, this is explained [here](https://sardana-controls.org/devel/howto_test/test_run_commands.html#sar-demo-test-environment).
So basically create Pool demo1 and MacroServer demo1, then connect to the door and run `sar_demo`. This should be enought to fix the errors that you get.
Also I recommend to restart these two servers everytime you run the test suite. 
Soon we plan to make each of the test independent of the external infrastructure.
Sorry about this inconveniences and thanks for testing Sardana!

**Comment by dschick** [comment]
okay, thanks a lot, I was not aware of this, now the test seems to run okayish.

**Comment by dschick** [comment]
----------------------------------------------------------------------
Ran 309 tests in 817.937s

OK (skipped=13, expected failures=2)
