### ISSUE TITLE
show/hide plots not working

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1251]
trying to show online scans and using the show/hide plots button in the expconf windows does not work and gives the following error messages in the spock window:

```
Traceback (most recent call last):                                                                   
  File "/home/labuser/Repos/sardana/src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py", line 707, in onPlotsButtonToggled
    self.__plotManager = DynamicPlotManager(self)
  File "/home/labuser/Repos/sardana/src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py", line 165, in __init__
    Qt.qApp.SDM.connectWriter("shortMessage", self, 'newShortMessage')
AttributeError: 'QApplication' object has no attribute 'SDM'

```
is this deprictaed due to #1042 ?

**Comment by cpascual** [comment]
> is this deprecated due to #1042 ?

Yes, I think so. Moreover, AFAIKT, the button is now obsolete since the [pyqtgraph-based online plot](https://github.com/reszelaz/sardana/pull/25/commits/94112bd8b1e938ad80c3bcc1c3af3591918234eb) was introduced in sardana 3.0.

I guess we should now  remove the button.
