### ISSUE TITLE
PMTV in compact mode raises expception on Taurus GUI start

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1292]
1. Create taurus newgui
2. Add a TaurusForm panel to the GUI and set a motor as the model
3. Change PMTV to compact mode
4. Close the GUI
5. Open the GUI

Then you get:

```
Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 394, in filterEvent
    self.handleEvent(*evt)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/input/tauruslineedit.py", line 151, in handleEvent
    self._updateValidator(evt_value)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/input/tauruslineedit.py", line 98, in _updateValidator
    bottom, top = attr.range
AttributeError: 'NoneType' object has no attribute 'range'
```

**Comment by HEnquist** [comment]
We cannot reproduce with Taurus 4.7.0 and sardana 3.1.1.
