### ISSUE TITLE
Axis Not ready when backlash is True in Move Multiple axes

### ISSUE THREAD

**Issue by jordiandreu** [sardana-org/sardana#1351]
In this example, the omegaz axis (axis 3) from an IcePAP system cannot be moved (Not Ready) when several motors are moved. It looks like the backlash motion of this motor is not protected and the overall motion of this axis is not atomic but intermixed with the motions of the other axes.
```
Dummy-12       INFO     2020-06-11 12:54:15,666 motor/eh_ipap_ctrl/27: write_Position(0.001675)
Dummy-12       DEBUG    2020-06-11 12:54:15,681 omega: Start motion user=0.001675, dial=-55.238850, backlash? False, dial_backlash=-55.238850
Dummy-12       INFO     2020-06-11 12:54:15,697 Controller.eh_ipap_ctrl: moveMultiple: [(27, -3185110.7999999989)]
SardanaTP.W010 DEBUG    2020-06-11 12:54:15,698 omega.Motion: -> action_loop
Dummy-12       INFO     2020-06-11 12:54:15,719 motor/eh_ipap_ctrl/5: write_Position(-0.211053169026)
Dummy-12       DEBUG    2020-06-11 12:54:15,730 centy: Start motion user=-0.211053, dial=3.738947, backlash? False, dial_backlash=3.738947
Dummy-12       INFO     2020-06-11 12:54:15,749 Controller.eh_ipap_ctrl: moveMultiple: [(5, 334635.74137213925)]
SardanaTP.W004 DEBUG    2020-06-11 12:54:15,750 centy.Motion: -> action_loop
Dummy-12       INFO     2020-06-11 12:54:15,777 motor/eh_ipap_ctrl/3: write_Position(-0.163)
Dummy-12       DEBUG    2020-06-11 12:54:15,784 omegaz: Start motion user=-0.163000, dial=4.308454, backlash? True, dial_backlash=4.312054
Dummy-12       INFO     2020-06-11 12:54:15,812 Controller.eh_ipap_ctrl: moveMultiple: [(3, 2171115.0)]
SardanaTP.W007 DEBUG    2020-06-11 12:54:15,813 omegaz.Motion: -> action_loop
Dummy-12       INFO     2020-06-11 12:54:15,839 motor/eh_ipap_ctrl/1: write_Position(0.134910336884)
SardanaTP.W007 DEBUG    2020-06-11 12:54:15,844 omegaz: Starting backlash
SardanaTP.W004 DEBUG    2020-06-11 12:54:15,849 centy: Stopped
Dummy-12       DEBUG    2020-06-11 12:54:15,853 omegax: Start motion user=0.134910, dial=5.536075, backlash? False, dial_backlash=5.536075
SardanaTP.W007 INFO     2020-06-11 12:54:15,884 Controller.eh_ipap_ctrl: moveMultiple: [(3, 2172904.9999999995)]
Dummy-12       ERROR    2020-06-11 12:54:15,899 Controller.eh_ipap_ctrl: StartAll([(3, 2172904.9999999995)]).
Exception:
Error sending command, IcePAP answered MOVE ERROR Cannot move axis 3: Axis is not ready

Dummy-12       ERROR    2020-06-11 12:54:15,900 omegax.Motion: eh_ipap_ctrl throws exception on StartAll. Stopping...
Dummy-12       DEBUG    2020-06-11 12:54:15,900 omegax.Motion: Details:
Traceback (most recent call last):
  File "/homelocal/sicilia/lib/python/site-packages/sardana/pool/poolmotion.py", line 242, in start_all
    pool_ctrl.ctrl.StartAll()
  File "/homelocal/sicilia/lib/python/site-packages/poolcontrollers/IcePAPCtrl.py", line 407, in StartAll
    self.ipap.move(self.move_multiple_grouped)
  File "/homelocal/sicilia/lib/python/site-packages/pyIcePAP/controller.py", line 258, in move
    self.send_cmd(cmd)
  File "/homelocal/sicilia/lib/python/site-packages/pyIcePAP/controller.py", line 245, in send_cmd
    return self._comm.send_cmd(cmd)
  File "/homelocal/sicilia/lib/python/site-packages/pyIcePAP/communication.py", line 104, in send_cmd
    raise RuntimeError(msg.format(ans))
RuntimeError: Error sending command, IcePAP answered MOVE ERROR Cannot move axis 3: Axis is not ready

Dummy-12       DEBUG    2020-06-11 12:54:15,901 omegax.Motion: emergency_break!!!!!!!!!!!
SardanaTP.W004 DEBUG    2020-06-11 12:54:15,904 centy.Motion: <- action_loop
SardanaTP.W007 DEBUG    2020-06-11 12:54:16,007 omegaz: Stopped
SardanaTP.W007 DEBUG    2020-06-11 12:54:16,032 omegaz.Motion: <- action_loop
```

**Comment by reszelaz** [comment]
The backlash move is not protected as any other interactions with the controller:

https://github.com/sardana-org/sardana/blob/b3e1c210a940680d684beb35ea5beeca41ff3b1a/src/sardana/pool/poolmotion.py#L286

The is a possiblity of race condition.
