### ISSUE TITLE
Signature of PreStartOne not clearly defined

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#1430]
Hi,

I was looking at our controllers and Ihave noticed that in `sardana/pool/controller.py`   we have defined
```python
 def PreStartOne(self, axis, value):
```
with two arguments while sometimes in the sardana code controllers are called with one argument 
```
sardana/pool/poolsynchronization.py:                    ret = pool_ctrl.ctrl.PreStartOne(axis)
```
and some tests.

Does it mean that signature of controllers should be
```python
def PreStartOne(self, axis, value=None):
```
like in some examples or one argument calls are buggy?

**Comment by reszelaz** [comment]
Hi Jan,
Many thanks for pointing this out!
I think that the only controller type which expects passing the `value` argument is the `MotorController`.
The `CounterTimerController` was reimplementing the _start_ methods to avoid the necessity to pass the `value` argument before https://github.com/sardana-org/sardana/pull/1362/commits/6f10a1747ad1ee13f4549ccd11daa6513529e543.
Just quickly thinking, the best would be to remove the `value` argument from the `Startable` interface and reimplement all the _start_ methods in the `MotorController`.

**Comment by reszelaz** [comment]
Sorry, I was not clear enough. I propose to just remove the `value` argument from the `PreStartOne()` and `StartOne()` from the `Startable` interface and have something like this:

```python

class Startable(object):
    """A Startable interface. A controller for which it's axis are 'startable'
    (like a motor, for example) should implement this interface

    .. note: Do not inherit directly from :class:`Startable`."""

    def PreStartAll(self):
        pass

    def PreStartOne(self, axis):
        return True

    def StartOne(self, axis):
        raise NotImplementedError("StartOne must be defined in the controller")

    def StartAll(self):
        pass
```

And then make the `Motor controller re-implement these two methods:

```python

    def PreStartOne(self, axis, value):
        return True

    def StartOne(self, axis, value):
        raise NotImplementedError("StartOne must be defined in the controller")
```

**Comment by jkotan** [comment]
Hi Zibi,

So if I understand correctly you propose some of controllers has the `value` parameters in `PreStartOne` and `StartOne` others not. And some of them are called by
```
sardana/pool/poolcontroller.py:984:            ctrl.StartOne(axis, dial_position)
sardana/pool/poolacquisition.py:932:                        pool_ctrl.ctrl.StartOne(axis, value)
sardana/pool/poolmotion.py:225:                ctrl.StartOne(axis, dial_position)
```
and others by
```
sardana/pool/poolsynchronization.py:234:                    pool_ctrl.ctrl.StartOne(axis)
```
and similarly for `PreStartOne`? It maybe quite misleading for users (otherwise you get errors like https://github.com/desy-fsec/sardana-controllers/pull/5). i.e. which controllers should have which parameters, i.e. better documentation.

I don't know. If you need to have a different number of parameters and two different calls of the method maybe it is good to have a different names of methods as well (but it will be not backward compatible). Or make value with default parameters for all (also not backward compatible). Anyhow all the changes requires reviewing of all controllers (and [Pre]StartOne(...) calls in sardana).
Hard to find a good solution.

**Comment by reszelaz** [comment]
I agree that it is not trivial to find a good solution here.

Before Sardana v3, the `CounterTimerController` was implementing the following methods (for simplicity I list here just the ones refering to a single axis):

```python
    def PreStartOneCT(self, axis):
         """￼
￼         .. deprecated:: 1.0
￼             use :meth:`~CounterTimerController.PreStartOne` instead"""
￼         return True
    def StartOneCT(self, axis):
         """￼
￼         .. deprecated:: 1.0
￼             use :meth:`~CounterTimerController.StartOne` instead"""
￼         return True

    def PreStartOne(self, axis, value=None):
        return self.PreStartOneCT(axis)

    def StartOne(self, axis, value=None):
        return self.StartOneCT(axis)
```
And it was also inheriting from the `Startable` interface. So it was changing the default `Startable` interface by giving a default value to the `value` argument.

As part of #1315 I have proposed #1362 to eliminate the deprecated methods with the `CT` suffix.

So to your idea:

> maybe it is good to have a different names of methods as well

We had it like this and this was deprecated. I don't know the original motivation of making it deprecated.

Furthermore, it was just the `CounterTimerController` which had these methods. For example other epxerimental channel controllers: `OneDController` and `TwoDController` were using the standard methods form the `Startable` interface.

IMHO it is not so bad to use the same method names with different signatures on different classes (`MotorController` or `TriggerGateController`).

Another discussion would be if we want to pass integration time / monitor counts to the `StartOne()` method of the experimental channels - this information is already loaded on the timer/monitor channel from the same controller. And as you pointed, for backwards compatibilty we would need to keep calling it with the integration time / monitor channels, but we may consider deprecating it. 

I agree with you that the documentation would need to be very clear about different signatures. Now it is not - see this [chapter](https://sardana-controls.org/devel/howto_controllers/howto_triggergatecontroller.html#start-a-trigger) where the code snippet does not use the `value` argument in `StartOne()` and the link points to the `Startable.StartOne()` method which does.

I wonder why you got the error described in https://github.com/desy-fsec/sardana-controllers/pull/5. Could it be that before you were defining the `StartOneCT(self, axis)` and when migrating to v3 you just changed the method name and not the arguments?

**Comment by jkotan** [comment]
Hi Zibi,

thank you for your detail explanations. The error you have mentioned above was caused by the fact the it is hard to understand the whole structure of sardana controllers. 
I'm still not sure if I get all the details. So to clarify your propose for StartOne()
```
Controller type                                  Signature
================================================================================
TriggerGateController                       def StartOne(self, axis):
CounterTimerController                      def StartOne(self, axis, value=None):
MotorController                             def StartOne(self, axis, value):
OneDController                              def StartOne(self, axis, value):
TwoDController                              def StartOne(self, axis, value):
```
and similarly for `PreStartOne`

Do we really need a default value of value  in the `CounterTimerController` case (I took it from sardana help and examples)?
If not it is better to remove it from examples and tests and dummy controllers.

So currently `StartOne` of `TriggerGateController` is execute at
   
    sardana/pool/poolsynchronization.py:234:                    pool_ctrl.ctrl.StartOne(axis)

while others at

    sardana/pool/poolcontroller.py:984:            ctrl.StartOne(axis, dial_position)
    sardana/pool/poolacquisition.py:932:           pool_ctrl.ctrl.StartOne(axis, value)
    sardana/pool/poolmotion.py:225:                ctrl.StartOne(axis, dial_position)

Does  `StartOne` of `CounterTimerController`  is executed in some special place, i.e. with one and with two parameters
so it needs the default value (None) for `value`?

**Comment by reszelaz** [comment]
> The error you have mentioned above was caused by the fact the it is hard to understand the whole structure of sardana controllers.

Sorry about that. We need to first improve the documentation and then think if the API for the controllers developers could be improved.

> I'm still not sure if I get all the details. So to clarify your propose for StartOne()
> 
> ```
> Controller type                                  Signature
> ================================================================================
> TriggerGateController                       def StartOne(self, axis):
> CounterTimerController                      def StartOne(self, axis, value=None):
> MotorController                             def StartOne(self, axis, value):
> OneDController                              def StartOne(self, axis, value):
> TwoDController                              def StartOne(self, axis, value):
> ```

Exactly, this is the current state. Note that we already [discuss](https://github.com/sardana-org/sardana/issues/1322#issuecomment-717973189) adding the _start_ methods to the `ZeroDController`. 
> 
> and similarly for `PreStartOne`
> 
> Do we really need a default value of value in the `CounterTimerController` case (I took it from sardana help and examples)?

> If not it is better to remove it from examples and tests and dummy controllers.

I think not, we don't need it. I fully agree to remove the default value.

My proposal was trying to go even further, to mark the `value` argument for all the controllers, but MotorController, as deprecated. This is simply because I don't have in mind a hardware that could profit from the value in `PreStartOne()` or `StartOne()` (again expluding motor controllers) but I may be wrong. Do you see it useful?

But to be practical, let's exclude this discussion from this issue and only focus the change of removing the `value` default value and on reviewing and correcting the docs. Do you think it is enough?

> 
> So currently `StartOne` of `TriggerGateController` is execute at
> 
> ```
> sardana/pool/poolsynchronization.py:234:                    pool_ctrl.ctrl.StartOne(axis)
> ```
> 
> while others at
> 
> ```
> sardana/pool/poolcontroller.py:984:            ctrl.StartOne(axis, dial_position)
> sardana/pool/poolacquisition.py:932:           pool_ctrl.ctrl.StartOne(axis, value)
> sardana/pool/poolmotion.py:225:                ctrl.StartOne(axis, dial_position)
> ```

Exactly.

> 
> Does `StartOne` of `CounterTimerController` is executed in some special place, i.e. with one and with two parameters
> so it needs the default value (None) for `value`?

AFAIK no.

**Comment by jkotan** [comment]
About usage of the value attribute in controllers @teresanunez has much bigger experience than me. @teresanunez what do you think?
From my side I would like to have as simple interface as possible and I don't like to remove back and for parameters because it is not backward compatible and one has to rewrite all the controllers.

**Comment by teresanunez** [comment]
I would prefer not to break the compatibility again, since I have just gone through all the controllers to adapt them to the
new API. If there is some mistake in the controllers it should be corrected (what would be well possible, I changed all of
 them at once without testing them), but not add new changes in the API.

**Comment by reszelaz** [comment]
Thanks for all your inputs!

My idea was to mark it as deprecated and to update the docs to the eventaul new API (without the `value` argument). Breaking the compatibility is not what I had in mind, at least now, cause this would imply releasing Sardana v4. Eventually in the future we could make this descission after, as always, agreement in the Community. As you remember removing the controller's deprecated API was done after 10 years from the time most of it was deprecated.

To me it would be helpful to know if someone uses the `value` argument in the experimental channel's controllers `StartOne()` or `PreStartOne()`. I may be perfectly wrong in my assumption that it is not needed there. We can discuss it on tomorrow's follow-up meeting.

Maybe let's first agree on removing the default value of the `value` argument from the `Startable.StartOne()` and `Startable.PreStartOne()`, correcting the documentation and examples (dummies). I think this won't break backwards compatibility and will make the signature more clear as @jkotan asks for.

**Comment by rhomspuron** [comment]
Hi, 

I found the problem with the TriggerGateController, it is mandatory to implement the PreStartOne(self, axis, value=None):
````
   desc = TypeError: PreStartOne() missing 1 required positional argument: 'value'
           
  origin = Traceback (most recent call last):
  File "/homelocal/rhoms/develop/pycharm/sardana/src/sardana/tango/pool/MeasurementGroup.py", line 307, in Start
    self.measurement_group.start_acquisition()
  File "/homelocal/rhoms/develop/pycharm/sardana/src/sardana/pool/poolmeasurementgroup.py", line 1362, in start_acquisition
    self.acquisition.run()
  File "/homelocal/rhoms/develop/pycharm/sardana/src/sardana/pool/poolacquisition.py", line 582, in run
    cb=self._synch._set_ready)
  File "/homelocal/rhoms/develop/pycharm/sardana/src/sardana/pool/poolaction.py", line 352, in run
    self.start_action(*args, **kwargs)
  File "/homelocal/rhoms/develop/pycharm/sardana/src/sardana/pool/poolsynchronization.py", line 230, in start_action
    ret = pool_ctrl.ctrl.PreStartOne(axis)
TypeError: PreStartOne() missing 1 required positional argument: 'value'

  reason = PyDs_PythonError
severity = ERR]

DevError[
    desc = Failed to execute command_inout on device mntgrp/pool_rhoms_1/rh_mnt_ni, command Start
  origin = Connection::command_inout()
  reason = API_CommandFailed
severity = ERR]
]

````
One possible solution is to fix the value=None on the Startable class, this fix the problem for all controller, if not the TriggerGateController should define this method.
