### ISSUE TITLE
Problems with moving motors with Tango polling

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1431]
I'm moving here a little bit old _one-time_ issue from ALBA with moving motors while polling the motor's state attribute.

The standard mv macro wass not able to finish due to an unexpected error.

The error points to the problems with retrieving the motor's state.

Further investigation points to the problems with following the Tango polling set for the State attribute of this motor, which was configured to 300ms.

```
SardanaTP.W007 DEBUG    2018-04-11 16:20:03,051 BL13/DOOR/01.Macro[scanexpose_microbeam_cont].Macro[mv]: Starting omegax movement to 0.0
--
SardanaTP.W007 ERROR    2018-04-11 16:20:04,148 tbl1301:10000.omegax.state.EG: Read error
SardanaTP.W007 DEBUG    2018-04-11 16:20:04,149 tbl1301:10000.omegax.state.EG: Details:
Traceback (most recent call last):
    File "/homelocal/sicilia/lib/python/site-packages/sardana/taurus/core/tango/sardana/pool.py", line 231, in read
        self.last_val = self._attr.read(cache=not force).value
    File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangoattribute.py", line 288, in read
        raise self.__attr_err
DevFailed: DevFailed[
DevError[
      desc = The polling thread is late and discard this object polling.
             Advice: Tune device server polling
    origin = PollThread::err_out_of_sync
    reason = API_PollThreadOutOfSync
  severity = ERR]
]
```

The polling was enabled for the MxCube needs (it needs to know about the motor's state changes even if the motor is not moved by Sardana).

Since the MxCube was not used at the moment the polling was relaxed to 1000ms.

**Comment by reszelaz** [comment]
One could try to reproduce it by enabling polling on state attribute and adding a `time.sleep()` in dummy motor controller `StateOne()`. Afterwards, running `mv` macro should trigger the problem.
