### ISSUE TITLE
scan with 2d channel gives error saving to hdf5

### ISSUE THREAD

**Issue by tiagocoutinho** [sardana-org/sardana#1498]
I am using latest sardana from develop and LimaCCDCtrl.

I try to do a scan using a dummy motor and a measurement group with only 1 channel being a 2D from LimaCCDCtrl.
The scan goes some predefined set of points so I am using a gscan with a generator behind the scenes.
I activate the RefEnabled True and I set it value ref to ":///tmp/lima/myth2_{index:04d}.h5" using expconf (BTW this seems very complicated).
I set scan variables with `newfile /tmp/lima/myth2.h5`

A the end of the scan I have the error:

```
Door_bl04_1 [14]: _myth2scan 0.1
Scan range is not defined for th and could not be verified against motor limits.
Operation will be saved in /tmp/lima/myth2.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #1 started at Fri Feb 12 15:02:38 2021. It will take at least 0:00:00.321593
 #Pt No      th      myth2       dt   
   0         -4     h5file:///tmp/lima/myth2_0011.h5  0.0401688
   1         -5     h5file:///tmp/lima/myth2_0012.h5  0.238222
   2         -3     h5file:///tmp/lima/myth2_0013.h5  0.436462
Operation saved in /tmp/lima/myth2.h5 (HDF5::NXscan)
Scan #1 ended at Fri Feb 12 15:02:39 2021, taking 0:00:00.644325. Dead time 53.4% (motion dead time 9.9%)
An error occurred while running _myth2scan:
ValueError: not enough values to unpack (expected 2, got 0)
Hint: in Spock execute `www`to get more details

Door_bl04_1 [15]: www
Traceback (most recent call last):
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/msmacromanager.py", line 1654, in runMacro
    for step in macro_obj.exec_():
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/macro.py", line 2355, in exec_
    for i in it:
  File "/home/tcoutinho/workspace/ALBA/mspd/mspd/sardana/macro/mythen2.py", line 49, in _myth2scan
    for step in _mythen_scan(self, mc, integ_time, positions):
  File "/home/tcoutinho/workspace/ALBA/mspd/mspd/sardana/macro/mythen2.py", line 18, in _mythen_scan
    for step in scan.step_scan():
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/scan/gscan.py", line 1054, in step_scan
    self.end()
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/scan/gscan.py", line 1005, in end
    self.data.end()
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/scan/scandata.py", line 505, in end
    self.datahandler.endRecordList(self)
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 61, in endRecordList
    recorder.endRecordList(recordlist)
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 126, in endRecordList
    self._endRecordList(recordlist)
  File "/home/tcoutinho/workspace/ALBA/sardana/src/sardana/macroserver/recorders/h5storage.py", line 386, in _endRecordList
    (dim_1, dim_2) = dd_env.shape
ValueError: not enough values to unpack (expected 2, got 0)

```

**Comment by reszelaz** [comment]
Hi @tiagocoutinho,

As we briefly talked about this today, it looks like you are missing the shape configuration in the `expconf`.
You must be using _almost the latest_ version from the develop branch. Currently in the develop branch the shape column already disappeared from the `expconf` - see #1466. If you update to the latest develop branch version you should not suffer this problems but the `LimaCCDCtrl` would need to be enhanced with the `GetAxisPar` handling the "shape" parameter according to ["Get 2D shape" documentation chapter](https://sardana-controls.org/devel/howto_controllers/howto_2dcontroller.html#get-2d-shape) - @rhomspuron is already aware of this new feature.

> I activate the RefEnabled True and I set it value ref to ":///tmp/lima/myth2_{index:04d}.h5" using expconf (BTW this seems very complicated).

Yes, it was already identified as _very poor user experience_ when we were working on SEP2. However we decided to keep the SEP2 scope to absolute minimum and implement this afterwards. I just created an issue for that: https://github.com/sardana-org/sardana/issues/1500.

**Comment by tiagocoutinho** [comment]
Ok thanks
I close it then
