### ISSUE TITLE
Missing macro hints make the Spock fail to start

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1589]
This issue still needs more investigation, but today @gjover reported problems after upgrading Sardana. 
At the Spock startup he experienced the following exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 939, in on_elements_changed
    return self._on_elements_changed(evt_src, evt_type, evt_value)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 958, in _on_elements_changed
    element = self._addElement(element_data)
  File "/usr/lib/python3/dist-packages/sardana/spock/spockms.py", line 619, in _addElement
    self._addMacro(element)
  File "/usr/lib/python3/dist-packages/sardana/spock/spockms.py", line 663, in _addMacro
    macro_fn.__doc__ = macro_info.doc + "\nWARNING: do not rely on the" \
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/sardana.py", line 95, in __getattr__
    return getattr(self.getObj(), name)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/sardana.py", line 130, in getObj
    self._object = obj = self._manager.getObject(self)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 926, in getObject
    obj = self._createMacroClassObject(element_info)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 932, in _createMacroClassObject
    return MacroInfo(from_json=element_info._data)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macro.py", line 64, in __init__
    self._buildDoc()
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macro.py", line 92, in _buildDoc
    if self.allowsHooks():
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macro.py", line 312, in allowsHooks
    self.hints["allowsHooks"]
TypeError: 'NoneType' object is not subscriptable
```

This is certainly related to #1523. We still need to discover which macros can lead to this situation.

**Comment by reszelaz** [comment]
After a little bit of investigation, I think I know what had happened here.

The MacroServer was still using an old Sardana version 3.0.3 while the client was already well advanced at commit 327bbd29.
In this case, the MacroServer had a bug fixed with #1422 which affects the new feature introduced by #1523 causing the above exception. 

I'm closing as won't fix. The solution is to use the same version of Sardana for the server and for the client.
