### ISSUE TITLE
DeviceProxy.subscribe_events and Sardana (SF#348)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#194]
Hi!
I would like to have a working non conflicting example for event subscription for real motors which have Sardana controllers. 

The task is the following, if Sardana motor has a TangoDevice attribute with motor address, I take this motor address and subscribe for its events, state change or position change. If I subscribe to Sardana motor, the updates happen not frequent enough, I want to have a more frequent updates. I want to have it for GUI.

Why I want to do that:
Current implementation of Taurus - TaurusAttribute is not robust enough (debian wheezy python-taurus 3.4.0-1.3). If I set Attribute polling by 100ms by attr.activatePolling(100), CPU load gets to 10-20% which is unacceptable if I want to use more than 1 attribute. 500ms polling takes 3-6% of CPU time. Even our simple hand made python.threading scripts running on the same PC with simultaneous polling of 10-20 attributes take much less CPU power (100ms + threading in normal regime, not idle).

The problem I have encountered with Sardana:
As long as I subscribe for event polling for state or position for a real Motor instance (OMS or TangoAttribute motor, etc) using threaded version of the following simplified code:

def setPolling(self, device_path):
d = PyTango.DeviceProxy(device_path)
self.device = d

attr = 'state'
if not d.is_attribute_polled(attr):
    d.poll_attribute(attr, poll_time)
else:
    # save polling state
    self._state_polled = True

self.__idstate = d.subscribe_event(attr, PyTango.EventType.CHANGE_EVENT, self.actionStateChange)

def cleanup(self):
    if isinstance(self.device, PyTango.DeviceProxy):
        try:
            attr = 'state'
            self.device.unsubscribe_event(self.__idstate)
            if not self._state_polled:
                d.stop_poll_attribute(attr)
        except DevFailed:
            pass

I can start and run my code with low CPU load on the machine running the client. 
Sardana macros like umvr work flawless even for large motor distances, but not the scans - dscan and ascan miserably fail, not always, but usual

So, Sardana scans stop to work with the following error messages - see below.
In my understanding Sardana is intended to be a general package working with Tango devices but not conflicting with other packages using somewhat similar or extended functionality. For instance I would like to have event subscription working inside my Sardana scripts running on Sardana MacroServer + GUI,  I would also like to understand the errors I have made in my code (if any) and general logic I should follow. May be I have missed some important points in documentation.

In addition - it would be also nice like to have a Sardana bug fix (moving scripts mvr, umvr) seem to be unaffected in contrast to scans).

I will also forward this mail to Tereza from DESY, it was simpler for me to submit a direct bug request. I would like of course to have this bug fix as soon as possible since PETRA-III at DESY will start user operation and we would really appreciate to have major some bugs to be fixed soon.

The complete test code I have used is attached.

Thanks for your hard work!
Cheers,
       Konstantin

BUG REPORT from a SPOCK session

Report: Stopped at step #325 with:
ceny_gp:
       State: Moving
      Status: ceny_gp is Moving (external)
              STATE(MOVING) LIM+(0) LIM-(0)
    Position: -0.9539 [CHANGING]
Returning to start positions...
An error occurred while running Macro 'dscan(ceny_gp, -1, 1, 1000, 0.05)':
state is not 'ON'

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 1135, in runMacro
    for step in macro_obj.exec_():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macro.py", line 2193, in exec_
    for i in it:
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macros/scan.py", line 250, in run
    for step in self._gScan.step_scan():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 799, in step_scan
    for i in self.scan_loop():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 855, in scan_loop
    self.stepUp(i, step, lstep)
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 888, in stepUp
    state, positions = motion.move(step['positions'])
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/motion.py", line 373, in move
    ret = moveable.move(new_pos, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 733, in go
    PoolElement.go(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 247, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 446, in go
    eid = self.start(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 247, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 416, in start
    self._start(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 722, in _start
    self.write_attribute('position', new_pos)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 165, in greener
    ret = submit(fn, self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 81, in synch_submit
    return get_synch_executor().submit(fn, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 73, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/device_proxy.py", line 964, in __DeviceProxy__write_attribute
    return self._write_attribute(*args, **kwargs)
DevFailed: DevFailed[
DevError[
    desc = state is not 'ON'
  origin = OmsVme58::setup_unit_move
  reason = OmsVme58 error
severity = ERR]

DevError[
    desc = Failed to write_attribute on device p02/motor/eh2b.42, attribute Position
  origin = DeviceProxy::write_attribute()
  reason = API_AttributeFailed
severity = ERR]

DevError[
    desc = Failed to write_attribute on device motor/omsvme58_eh2b/42, attribute position
  origin = DeviceProxy::write_attribute()
  reason = API_AttributeFailed
severity = ERR]
]

p02/door/door.01 [27]: dscan ceny_gp -.1 .1 10 0.05
Operation will be saved in /tmp/scan_01166.nxs (nxs)
Scan #1166 started at Wed Apr 15 14:53:19 2015. It will take at least 0:00:00.550750
Moving to start positions...
                                                                                 petra             
                                                                                globals            
                                                                                keyword            
 #Pt No   ceny_gp   eh2b_t01  eh2b_vfc01  eh2b_vfc02  eh2b_vfc03  eh2b_vfc04  BeamCurrent     dt   
   0      -0.7019     0.05       76.5        74.5        64.5         0        0.00836048  8.18461 
   1      -0.7017     0.05        76         74.5        63.5         0        0.00836048  8.45843 
Report: Stopped at step #2 with:
ceny_gp:
       State: Moving
      Status: ceny_gp is Moving (external)
              STATE(MOVING) LIM+(0) LIM-(0)
    Position: -0.6852 [CHANGING]
Returning to start positions...
Failed to execute macro 'do_restore'
An error occurred while running Macro 'dscan(ceny_gp, -.1, .1, 10, 0.05)':
state is not 'ON'

p02/door/door.01 [28]: www 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 1135, in runMacro
    for step in macro_obj.exec_():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macro.py", line 2193, in exec_
    for i in it:
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macros/scan.py", line 250, in run
    for step in self._gScan.step_scan():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 799, in step_scan
    for i in self.scan_loop():
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 855, in scan_loop
    self.stepUp(i, step, lstep)
  File "/usr/lib/python2.7/dist-packages/sardana/macroserver/scan/gscan.py", line 888, in stepUp
    state, positions = motion.move(step['positions'])
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/motion.py", line 373, in move
    ret = moveable.move(new_pos, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 733, in go
    PoolElement.go(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 247, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 446, in go
    eid = self.start(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 247, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 416, in start
    self._start(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/pool.py", line 722, in _start
    self.write_attribute('position', new_pos)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 165, in greener
    ret = submit(fn, self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 81, in synch_submit
    return get_synch_executor().submit(fn, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/green.py", line 73, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PyTango/device_proxy.py", line 964, in __DeviceProxy__write_attribute
    return self._write_attribute(*args, **kwargs)
DevFailed: DevFailed[
DevError[
    desc = state is not 'ON'
  origin = OmsVme58::setup_unit_move
  reason = OmsVme58 error
severity = ERR]

DevError[
    desc = Failed to write_attribute on device p02/motor/eh2b.42, attribute Position
  origin = DeviceProxy::write_attribute()
  reason = API_AttributeFailed
severity = ERR]

DevError[
    desc = Failed to write_attribute on device motor/omsvme58_eh2b/42, attribute position
  origin = DeviceProxy::write_attribute()
  reason = API_AttributeFailed
severity = ERR]
]

Reported by: [lorcata@SF](http:/sf.net/u/lorcata) ( http://sf.net/u/lorcata )

Original Ticket: [sardana/tickets/348](https://sourceforge.net/p/sardana/tickets/348)

**Comment by reszelaz** [comment]
After talking to @teresanunez it seems that the problems were solved or workaround - she did not receive more feedback. Closing...
