### ISSUE TITLE
test ReadMotorPositionOutsideLim  fails on Windows (SF#376)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#222]
Test sardana.tango.pool.test.test_Motor.ReadMotorPositionOutsideLim does not work on Windows (was tried on Windows7, ServicePack 1, 64 bits)

Error when run within testsuite:

```
======================================================================
ERROR: test_read_position_outside_sw_lim (tango.pool.test.test_Motor.ReadMotorPositionOutsideLim)
Test bug #238: reading position when motor is out of SW lims.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\sardana\tango\pool\test\test_Motor.py", line 40, in setUp
    super(ReadMotorPositionOutsideLim, self).setUp()
  File "C:\Python27\Lib\site-packages\sardana\tango\pool\test\base.py", line 67, in setUp
    self._starter.startDs()
  File "C:\Python27\Lib\site-packages\taurus\core\tango\starter.py", line 105, in startDs
    self.start()
  File "C:\Python27\Lib\site-packages\taurus\core\tango\starter.py", line 211, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

----------------------------------------------------------------------
Ran 29 tests in 26.319s

FAILED (errors=1)
```

Error when run as a separate test:

```
C:\Users\sicilia>python -m unittest sardana.tango.pool.test.test_Motor.ReadMotorPositionOutsideLim
MainThread     INFO     2015-07-23 12:22:46,480 Starter: Starting server Pool/win_2...
E
======================================================================
ERROR: test_read_position_outside_sw_lim (sardana.tango.pool.test.test_Motor.ReadMotorPositionOutsid
Test bug #238: reading position when motor is out of SW lims.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\sardana\tango\pool\test\test_Motor.py", line 40, in setUp
    super(ReadMotorPositionOutsideLim, self).setUp()
  File "C:\Python27\Lib\site-packages\sardana\tango\pool\test\base.py", line 68, in setUp
    self._starter.startDs()
  File "C:\Python27\Lib\site-packages\taurus\core\tango\starter.py", line 105, in startDs
    self.start()
  File "C:\Python27\Lib\site-packages\taurus\core\tango\starter.py", line 211, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

----------------------------------------------------------------------
Ran 1 test in 0.099s
```

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/376](https://sourceforge.net/p/sardana/tickets/376)

**Comment by sagiss** [comment]
After creating Pool and MS from scratch, this test (test_read_position_outside_sw_lim) does not fail anymore. See attached image.

![win7_tests](https://cloud.githubusercontent.com/assets/1327426/21455789/6d8d53c8-c923-11e6-8418-2e4b77aaeb01.jpg)
We will close the ticket
