### ISSUE TITLE
Unhandled exception when a motion ends in an alarm state

### ISSUE THREAD

**Issue by LJBD** [sardana-org/sardana#467]
Hello!

I've found a bug in motion macros: when a motion ends in an alarm state, the following message is show in spock:
```python
Door_fresh-222_1 [2]: umv mot13 -1
     mot13
    0.0000
Motion ended in DevState.ALARM
An error occurred while running Macro 'umv([['mot13', '-1.0']]) -> 3c351c36-4144-11e7-a967-000c295e4c94':
cannot concatenate 'str' and 'list' objects
``` 
I've set the lower limit switch of this dummy axis to 0, so that this movement should hit it. I've tested this with `umv`, `mv`, `dscan` and `ascan`. I've got Sardana 2.2.2, Taurus 4.0.3, Tango 9.2.5a and PyTango 9.2.1.

On the server side logs look like that:
```python
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,247 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.ALARM: 11>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'State', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 246318), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.ALARM, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 246318), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,333 TaurusRootLogger: TangoAttrValue{'wvalue': <Quantity(-1.0, 'dimensionless')>, '_attrRef': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'rvalue': <Quantity(0.0, 'dimensionless')>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'Position', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 332495), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = -1.0), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 332495), 'error': None, 'config': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,365 TaurusRootLogger: TangoAttrValue{'wvalue': <Quantity(-1.0, 'dimensionless')>, '_attrRef': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'rvalue': <Quantity(0.0, 'dimensionless')>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'Position', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 364397), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = -1.0), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 364397), 'error': None, 'config': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,365 Door/fresh-222/1.MacroExecutor: [START] runMacro Macro 'umv([['mot13', '-1.0']]) -> 3c351c36-4144-11e7-a967-000c295e4c94'
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,365 Door/fresh-222/1.Macro[umv]: Executing macro: mv
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,366 Door/fresh-222/1.MacroExecutor: [START] runMacro Macro 'mv([['mot13', '-1.0']]) -> -1'
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,366 Door/fresh-222/1.Macro[umv].Macro[mv]: Starting mot13 movement to -1.0
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,368 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.ALARM: 11>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'State', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 246318), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.ALARM, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 246318), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 INFO     2017-05-25 14:18:18,368 motor/motctrl04/1: write_Position(-1.0)
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,369 mot13: Start motion user=-1.000000, dial=-1.000000, backlash? False, dial_backlash=-1.000000
SardanaTP.W002 DEBUG    2017-05-25 14:18:18,380 mot13.Motion: -> action_loop
SardanaTP.W002 ERROR    2017-05-25 14:18:18,381 mot13.Motion: Loop read state error
SardanaTP.W002 INFO     2017-05-25 14:18:18,381 Controller.motctrl04: AbortOne(1)
SardanaTP.W002 DEBUG    2017-05-25 14:18:18,387 mot13.Motion: <- action_loop
Dummy-4        DEBUG    2017-05-25 14:18:18,389 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.MOVING: 6>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'state', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388716), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.MOVING, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388716), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
Dummy-4        DEBUG    2017-05-25 14:18:18,390 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.MOVING: 6>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'state', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388716), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.MOVING, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388716), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
Dummy-4        DEBUG    2017-05-25 14:18:18,391 TaurusRootLogger: TangoAttrValue{'wvalue': <Quantity(-1.0, 'dimensionless')>, '_attrRef': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'rvalue': <Quantity(0.0, 'dimensionless')>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'position', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 381800), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = -1.0), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 381800), 'error': None, 'config': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'quality': <AttrQuality.ATTR_VALID: 0>}
Dummy-4        OUTPUT   2017-05-25 14:18:18,391 Door/fresh-222/1.Macro[umv]: <BLOCK>
     mot13
    0.0000
</BLOCK>
Dummy-4        DEBUG    2017-05-25 14:18:18,392 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.ALARM: 11>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'state', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.ALARM, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
Dummy-4        DEBUG    2017-05-25 14:18:18,393 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.ALARM: 11>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'state', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.ALARM, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,393 TaurusRootLogger: TangoAttrValue{'wvalue': None, '_attrRef': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'rvalue': <DevState.ALARM: 11>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'state', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), type = tango._tango.CmdArgType.DevState, value = tango._tango.DevState.ALARM, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 388972), 'error': None, 'config': <weakproxy at 0x7fd2ac036158 to TangoAttribute at 0x7fd29c04e550>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,394 TaurusRootLogger: TangoAttrValue{'wvalue': <Quantity(-1.0, 'dimensionless')>, '_attrRef': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'rvalue': <Quantity(0.0, 'dimensionless')>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'position', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 381800), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = -1.0), 'time': TimeVal(tv_nsec = 0, tv_sec = 1495714698, tv_usec = 381800), 'error': None, 'config': <weakproxy at 0x7fd2ac0365d0 to TangoAttribute at 0x7fd2ac0c4ad0>, 'quality': <AttrQuality.ATTR_VALID: 0>}
SardanaTP.W001 WARNING  2017-05-25 14:18:18,394 Door/fresh-222/1.Macro[umv].Macro[mv]: Motion ended in DevState.ALARM
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,395 Door/fresh-222/1.MacroExecutor: Sending exception event
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,395 Door/fresh-222/1.MacroExecutor: [ENDEX] (MacroServerException) runMacro mv
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,397 Door/fresh-222/1.MacroExecutor: Sending exception event
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,398 Door/fresh-222/1.MacroExecutor: [ENDEX] (MacroServerException) runMacro umv
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,398 Door/fresh-222/1: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/msmacromanager.py", line 1224, in runMacro
    for step in macro_obj.exec_():
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/macro.py", line 2238, in exec_
    res = self.run(*self._in_pars)
  File "/usr/lib/python2.7/site-packages/sardana/macroserver/macros/standard.py", line 448, in run
    msg.append(motor.information())
  File "/usr/lib/python2.7/site-packages/sardana/taurus/core/tango/sardana/pool.py", line 485, in information
    msg = self._information(tab=tab)
  File "/usr/lib/python2.7/site-packages/sardana/taurus/core/tango/sardana/pool.py", line 807, in _information
    msg = PoolElement._information(self, tab=tab)
  File "/usr/lib/python2.7/site-packages/sardana/taurus/core/tango/sardana/pool.py", line 502, in _information
    msg.append(tab + "   State: " + state)
TypeError: cannot concatenate 'str' and 'list' objects

SardanaTP.W001 ERROR    2017-05-25 14:18:18,398 Door/fresh-222/1: An error occurred while running Macro 'umv([['mot13', '-1.0']]) -> 3c351c36-4144-11e7-a967-000c295e4c94':
cannot concatenate 'str' and 'list' objects
SardanaTP.W001 DEBUG    2017-05-25 14:18:18,398 Door/fresh-222/1.MacroExecutor: Job ended (stopped=False, aborted=False)
```

**Comment by reszelaz** [comment]
Confirmed with Taurus4. With Taurus3 there is no problem.

The problem seems to be the new `TaurusDevice.state` member which is a pure Taurus concept now. More about it in [TEP14](https://github.com/taurus-org/taurus/blob/develop/doc/source/tep/TEP14.md#scheme-agnostic-api-for-xxxdevice).
