### ISSUE TITLE
TwoDExpChannel: 'Value' object has no attribute 'value_buffer'

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#486]
Hi,

I've just wanted to test sardana from the current develop branch and with 2D channel (pilatus)
I get the following error:

    SardanaTP.W001 DEBUG    2017-06-30 07:47:53,062 p09/door/haso228k.01: Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1251, in runMacro
	for step in macro_obj.exec_():
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/macro.py", line 2274, in exec_
	for i in it:
      File "/usr/lib/python2.7/dist-packages/sardana/macroserver/macros/scan.py", line 256, in run
	for step in self._gScan.step_scan():
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/scan/gscan.py", line 877, in step_scan
	self.start()
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/scan/gscan.py", line 832, in start
	self.data.start()
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/scan/scandata.py", line 289, in start
	self.datahandler.startRecordList(self)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/scan/recorder/datarecorder.py", line 56, in startRecordList
	recorder.startRecordList(recordlist)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/macroserver/scan/recorder/datarecorder.py", line 115, in startRecordList
	self._startRecordList(recordlist)
      File "/usr/lib/python2.7/dist-packages/sardananxsrecorder/nxsrecorder.py", line 808, in _startRecordList
	self.__setNexusDevices()
      File "/usr/lib/python2.7/dist-packages/sardananxsrecorder/nxsrecorder.py", line 438, in __setNexusDevices
	self.__command(self.__nexussettings_device, "updateMntGrp")
      File "/usr/lib/python2.7/dist-packages/sardananxsrecorder/nxsrecorder.py", line 149, in __command
	return server.command_inout(command)
      File "/usr/lib/python2.7/dist-packages/tango/green.py", line 266, in greener
	ret = submitter(fn, self, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tango/green.py", line 100, in submit
	return fn(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tango/connection.py", line 101, in __Connection__command_inout
	r = Connection.command_inout_raw(self, name, *args, **kwds)
      File "/usr/lib/python2.7/dist-packages/tango/connection.py", line 127, in __Connection__command_inout_raw
	return self.__command_inout(cmd_name, param)
    DevFailed: DevFailed[
    DevError[
	desc = AttributeError: 'Value' object has no attribute 'value_buffer'

      origin =   File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/tango/pool/PoolDevice.py", line 375, in _read_DynamicAttribute
	return read(attr)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/tango/pool/TwoDExpChannel.py", line 177, in read_Value
	if not use_cache and len(twod.value.value_buffer) > 0:

      reason = PyDs_PythonError
    severity = ERR]

    DevError[
	desc = Failed to read_attribute on device expchan/pilatus300kpilatusctrl/1, attribute Value
      origin = DeviceProxy::read_attribute()
      reason = API_AttributeFailed
    severity = ERR]

    DevError[
	desc = Failed to execute command_inout on device p09/nxsrecselector/haso228k, command updateMntGrp
      origin = Connection::command_inout()
      reason = API_CommandFailed
    severity = ERR]
    ]

    SardanaTP.W001 ERROR    2017-06-30 07:47:53,062 p09/door/haso228k.01: An error occurred while running Macro 'ascan(exp_mot20, 0.0, 10.0, 3, 0.1) -> a6c09510-5d57-11e7-b27b-00224d6ad779':
    AttributeError: 'Value' object has no attribute 'value_buffer'

    SardanaTP.W001 DEBUG    2017-06-30 07:47:53,062 p09/door/haso228k.01.MacroExecutor: Job ended (stopped=False, aborted=False)

Bests,
Jan

**Comment by teresanunez** [comment]
Hi Jan,
                 there were changes in the implementation of 1D and 2D, mainly related to the continuous
scans. I would say that we (myself) have to review the DESY controllers and see in detail where is the
problem. @reszelaz, I can take care of this as soon as possible. We are not going to use this in our
 beamlines just now. 
                                         Regards,
                                                         Teresa

**Comment by jkotan** [comment]
Hi Teresa,

Thanks for your quick answer. So it means the "user interface" is no more backward compatible. I think it would be good to name the new version of Sardana 3.0.0 (instead of 2.2.5).

Bests,
Jan

**Comment by reszelaz** [comment]
Thanks for the report! There should be no backwards incompatibilities. What you found is probably a bug. I will check it ASAP but currently I have some problems with my PC after the OS upgrade... I ask you for some patience:)

@teresanunez thanks for the help offer! We should check it first with dummies, cause most probably the error should be reproducible there.

**Comment by teresanunez** [comment]
HI @reszelaz, I think you have make a copy/paste from ZeroD to TwoD ... I can solve the problem 
correcting the file TwoDExpChannel.py.

**Comment by reszelaz** [comment]
It's very probable, please make a PR so I will merge it after a visual check (I'm still without a fully-working environment..)

**Comment by reszelaz** [comment]
@jkotan, after applying @teresanunez solution it works for me. Please test it and let us know if it also works for you. Thanks!

**Comment by jkotan** [comment]
Hi Teresa and Zibi,

Yes. The error is fixed. Thanks.

Cheers,
Jan
