### ISSUE TITLE
taurusgui macrogui crashes with Segmentation fault

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#488]
Hi,

When I run 'taurusgui macrogui' and in the macro widget I select ascan command from history taurusgui 
crashes with the following error:

    AttributeError: 'SingleParamNode' object has no attribute '_type'
    MainThread     ERROR    2017-06-30 08:17:54,938 LogExceptHook: Unhandled exception:
    Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/model.py", line 64, in flags
	not node.type() in globals.EDITOR_NONEDITABLE_PARAMS):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/taurus/core/tango/sardana/macro.py", line 511, in type
	return self._type
    AttributeError: 'SingleParamNode' object has no attribute '_type'
    MainThread     ERROR    2017-06-30 08:19:39,825 LogExceptHook: Unhandled exception:
    Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/model.py", line 64, in flags
	not node.type() in globals.EDITOR_NONEDITABLE_PARAMS):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/taurus/core/tango/sardana/macro.py", line 511, in type
	return self._type
    AttributeError: 'SingleParamNode' object has no attribute '_type'
    Segmentation fault

Bests,
Jan

**Comment by cpascual** [comment]
I think this (#488) may be a duplicate of #441 and probably of #18

**Comment by cpascual** [comment]
(and I wonder if #35 is also related...

**Comment by reszelaz** [comment]
I've just merged #35 into #18.

@jkotan could it be that you try to select a macro from the history before actually selecting the MacroServer and Door in the menu Taurus->Macro Server Configuration? If yes I confirm that this is the same as #18. In this case I would close this issue as duplicate.

#488 is a different one, that just affects the favorites list.

**Comment by jkotan** [comment]
I get this error after selecting  Taurus->Macro Server Configuration MacroServer and Door.

**Comment by teresanunez** [comment]
Hi, I have checked it by myself. It is the same bug reported in #18 in the comment starting with:

"Fri Mar 30 13:09:49 2012 cpascual:"

Defining MACROSERVER_NAME and DOOR_NAME in the config file the problem disapears.

**Comment by reszelaz** [comment]
Thanks to both for investigating this. If it is indeed the same thing that described in #18 I propose to close this as duplicate.

**Comment by jkotan** [comment]
Sure. Probably is the same big. Thanks
