### ISSUE TITLE
Unable to pause Null macro

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#640]
In a macrobutton if you abort quickly  a macro like ct 3. The macroserver is hung due to  API_CommandTimedOut

```
MacroServer cfalcon
MainThread     ERROR    2017-11-02 14:59:14,377 ModuleManager: Invalid module MadRecorder
MainThread     ERROR    2017-11-02 14:59:14,758 ModuleManager: Invalid module test_pmac
MainThread     ERROR    2017-11-02 14:59:14,780 ModuleManager: Invalid module BL22_CLAESS_pseudomotors
MainThread     ERROR    2017-11-02 14:59:14,816 ModuleManager: Invalid module bl01_macros
Unable to pause Null macro
SardanaTP.W002 ERROR    2017-11-02 14:59:26,350 SardanaTP.SardanaTP.W002: Uncaught exception running job '_abort' called from thread Dummy-1:
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/macroserver/Door.py", line 366, in AbortMacro
    self.macro_executor.abort()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/macroserver/msmacromanager.py", line 1128, in abort
    self.macro_server.add_job(self._abort, self._setAbortDone)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/macroserver/macroserver.py", line 172, in add_job
    th_pool.add(job, callback, *args, **kw)
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/util/threadpool.py", line 132, in run
    callback(cmd(*args, **kw))
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/macroserver/msmacromanager.py", line 1137, in _abort
    m.abort()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/macroserver/macro.py", line 2346, in abort
    Logger.debug(self, "Aborting...")
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/util/log.py", line 728, in debug
    self.log_obj.debug(msg, *args, **kw)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/attributehandler.py", line 53, in emit
    self.sendText(output)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/attributehandler.py", line 63, in sendText
    dev.set_attribute(attr, output)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 292, in set_attribute
    synch=synch)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 313, in set_attribute_push
    error=error, priority=priority)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 406, in _set_attribute_push
    self.push_change_event(*args)
DevFailed: DevFailed[
DevError[
    desc = Not able to acquire serialization (dev, class or process) monitor
  origin = TangoMonitor::get_monitor
  reason = API_CommandTimedOut
severity = ERR]
]
```

**Comment by reszelaz** [comment]
Some time ago, with @jordiandreu we have seen the same error at the beamline when aborting a macro with the macrobutton. In that case it was not 100% reproducible but quite often. At that time I could not reproduce it in my development environment so it is nice that you found a way to reproduce it.

@jordiandreu could you describe exactly your error and maybe paste the traceback message. I also remember that we have applied a local patch at the beamline that was able to avoid this errors. It could be also usefull if you paste it here.

**Comment by mrosanes** [comment]
I have reproduced the error, after many many tries. With taurus and sardana develop. Thus the bug also exists using taurus4.
Still I find no easy way to reproduce it for the moment.

Independent thing that I have observed with the macrobutton behavior:
Sometimes I also observe that the macrobutton can become frozen, till another macro is launched from spock. Then it recovers the focus and the macrobutton works again.
