### ISSUE TITLE
PMTV reports errors in the Pool

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#652]
The Pool reports uncaught exception  and type errors when you move  a motor from a PMTV.
```
ventTH.W001   ERROR    2017-11-21 16:44:41,135 EventTH.EventTH.W001: Uncaught exception running job 'set_attribute_push' called from thread SardanaTP.W001:
  File "/usr/lib64/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolaction.py", line 454, in _asynch_action_loop
    self.action_loop()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/util/log.py", line 190, in wrapper
    ret = f(*args, **kwargs)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotion.py", line 384, in action_loop
    moveable.get_position(cache=False, propagate=2)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotor.py", line 619, in get_position
    position.update(cache=cache, propagate=propagate)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotor.py", line 183, in update
    self.get_dial().update(cache=cache, propagate=propagate)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotor.py", line 191, in update
    self.set_value(dial_position_value, propagate=propagate)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaattribute.py", line 125, in set_value
    propagate=propagate)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaattribute.py", line 134, in _set_value
    self.fire_read_event(propagate=propagate)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaattribute.py", line 281, in fire_read_event
    self.fire_event(evt_type, self)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotor.py", line 180, in on_change
    self.fire_read_event(propagate=evt_type.priority)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaattribute.py", line 281, in fire_read_event
    self.fire_event(evt_type, self)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotorgroup.py", line 102, in on_change
    self.fire_read_event(propagate=evt_type.priority)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaattribute.py", line 281, in fire_read_event
    self.fire_event(evt_type, self)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/pool/poolmotorgroup.py", line 138, in on_change
    self.fire_event(evt_type, evt_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanabase.py", line 130, in fire_event
    listeners=listeners)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/pool/MotorGroup.py", line 93, in on_motor_group_changed
    self._on_motor_group_changed(event_source, event_type, event_value)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/pool/MotorGroup.py", line 138, in _on_motor_group_changed
    priority=priority, error=error, synch=False)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 297, in set_attribute
    priority=priority, synch=synch)
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 309, in set_attribute_push
    error=error, priority=priority)
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/tango/core/SardanaDevice.py", line 393, in _set_attribute_push
    ' out of range (w_value=%f)' % w_value)
TypeError: float argument required, not list

```

**Comment by reszelaz** [comment]
I'm not able to reproduce it. The exception points to some issue related with the motor group. I've a motor group defined on top of the motor that I move from the PMTV, but no error occurs on the Pool side. Maybe you have some incosistent motor groups in your system?

**Comment by cmft** [comment]
@reszelaz you are right!!

Thanks.
