### ISSUE TITLE
fake/duplicate counter implementation

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#812]
Hej all,

some time ago I was asking for a way how to hack Sardana in order to duplicate counters for the case when one toggles/alternates one motor (such as a magnetic field, laser, or dark count measurement), see this [mailing list post](https://sourceforge.net/p/sardana/mailman/message/36318971/)

Instead of nesting two scans or doing a mesh scan, I really want to fake/duplicate some of my counters when I toggle my magnetic field at every scan point, e.g. of a spectrum --> XMCD measurement, because then then both counters are also all within one scan in Sardana, SPEC, PyMCA, etc.

I first realized this using a TangoDeviceServer for storing my counter values, many thanks to @teresanunez , because of a bug in Tango under Windows, see #769 and tango-controls/TangoTickets#19.

Now, I finally moved to Linux and could realize my initial version which I would like to share here:

1. I hook a macro called `user_pre_acq` to the generalHookPlace` pre-acq`. When I am doing such a toggle scan, I set an `env` variable `altOn=True` and in `user_pre_acq` I execute an initial acquisition for negative magnetic fields:

```
if altOn:
        # move magnet to minus amplitude
        kepco = self.getMotor("kepco")
        kepco.move(-1*ampl)
        
        parent = self.getParentMacro()
        if parent:
            integ_time = parent.integ_time
            mnt_grp = self.getObj(self.getEnv('ActiveMntGrp'), type_class=Type.MeasurementGroup)
            state, data = mnt_grp.count(integ_time)
                       
        kepco.move(+1*ampl)
```

afterwards the normal acquisiton takes place for positive field.
I then created a PseudoCounter which stores the counter values from the real physical counters for negative field, while the positive field values are acquired during the second acquisition and thus stored in the physical counters:

```
from sardana.pool.controller import PseudoCounterController
import PyTango

class pseudoCounterAltOn(PseudoCounterController):
    """ A simple pseudo counter which receives two counter values (I and I0)
        and returns I/I0"""

    counter_roles        = ('Det', 'I0',)
    pseudo_counter_roles = ('DetM','I0M',)
    value = [0]*2

    def Calc(self, axis, counters):
        counter = counters[axis-1]
        
        kepco = PyTango.DeviceProxy("motor/kepcoctrl/0")
        field = kepco.position
      
        if field < 0:
            self.value[axis-1] = counter        

        return self.value[axis-1]
```
Actually this line:
 `kepco = PyTango.DeviceProxy("motor/kepcoctrl/0")`
did not work under windows, so I could no read the position of the magnet from within the counters.

Maybe this is also for interest for someone else.
Any comments are of course welcome.

**Comment by dschick** [comment]
I was a bit too confident about my solution :(
It actually worked until I restarted Sardana.
Now I get the following error, exactly for the pseudoCounter `pc/altonctrl/1` of class `pseudoCounterAltOn `as introduced above:
```

MainThread     DEBUG    2018-07-06 02:24:11,754 pc/altonctrl/1: <- (with AttributeError) init_device
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/log.py", line 190, in wrapper
    ret = f(*args, **kwargs)
  File "/home/moke/Repos/sardana/src/sardana/tango/pool/PseudoCounter.py", line 87, in init_device
    ctrl_id=self.Ctrl_id, user_elements=self.Elements)
  File "/home/moke/Repos/sardana/src/sardana/pool/pool.py", line 470, in create_element
    elem = klass(**kwargs)
  File "/home/moke/Repos/sardana/src/sardana/pool/poolpseudocounter.py", line 227, in __init__
    pool=kwargs['pool'])
  File "/home/moke/Repos/sardana/src/sardana/pool/poolbasegroup.py", line 60, in __init__
    self.info("failed to build element information. No problem. "
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/log.py", line 833, in info
    self.log_obj.info(msg, *args, **kw)
AttributeError: 'PoolPseudoCounter' object has no attribute 'log_obj'
MainThread     INFO     2018-07-06 02:24:11,755 TaurusRootLogger: Exiting
MainThread     CRITICAL 2018-07-06 02:24:11,756 TaurusRootLogger: Server exited with DevFailed
Traceback (most recent call last):
  File "/home/moke/Repos/sardana/src/sardana/tango/core/util.py", line 1073, in run_tango_server
    util.server_init()
DevFailed: DevFailed[
DevError[
    desc = AttributeError: 'PoolPseudoCounter' object has no attribute 'log_obj'
           
  origin =   File "/usr/lib/python2.7/dist-packages/tango/device_class.py", line 568, in __DeviceClass__device_factory
    device = self._new_device(deviceImplClass, klass, dev_name)
  File "/usr/lib/python2.7/dist-packages/tango/device_class.py", line 547, in __DeviceClass__new_device
    return klass(dev_class, dev_name)
  File "/home/moke/Repos/sardana/src/sardana/tango/pool/PseudoCounter.py", line 51, in __init__
    PoolExpChannelDevice.__init__(self, dclass, name)
  File "/home/moke/Repos/sardana/src/sardana/tango/pool/PoolDevice.py", line 833, in __init__
    PoolElementDevice.__init__(self, dclass, name)
  File "/home/moke/Repos/sardana/src/sardana/tango/pool/PoolDevice.py", line 67, in __init__
    SardanaDevice.__init__(self, dclass, name)
  File "/home/moke/Repos/sardana/src/sardana/tango/core/SardanaDevice.py", line 91, in __init__
    self.init_device()
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/log.py", line 190, in wrapper
    ret = f(*args, **kwargs)
  File "/home/moke/Repos/sardana/src/sardana/tango/pool/PseudoCounter.py", line 87, in init_device
    ctrl_id=self.Ctrl_id, user_elements=self.Elements)
  File "/home/moke/Repos/sardana/src/sardana/pool/pool.py", line 470, in create_element
    elem = klass(**kwargs)
  File "/home/moke/Repos/sardana/src/sardana/pool/poolpseudocounter.py", line 227, in __init__
    pool=kwargs['pool'])
  File "/home/moke/Repos/sardana/src/sardana/pool/poolbasegroup.py", line 60, in __init__
    self.info("failed to build element information. No problem. "
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/log.py", line 833, in info
    self.log_obj.info(msg, *args, **kw)

  reason = PyDs_PythonError
severity = ERR]
]
MainThread     INFO     2018-07-06 02:24:11,756 TaurusRootLogger: Exited

```

It is actually reproducable, that it is working well when I remove all pseudoCounters of this kind and start with a new measurementGroup and then add the pseudocounters again (always without restarting Sardana). After restarting the pool, I then get the error.

**Comment by teresanunez** [comment]
HI @dschick, i have not tried ... but my first idea ... "motor/kepcoctrl/0" is a motor from the Pool?.
If this is the case I would say that the problem is that the PseudoCounter pool device is created before
 the Pool Motor and you get errors because of that. But as I said, it is only one idea without testing or
 trying. Could you try to put there a device from outside the Pool and see what happens?.

**Comment by dschick** [comment]
@teresanunez thanks for the comment. This was also my first guess.
However, after some debugging, it seems, that the problem is, that I created a pseudoCounter with another pseudoCounter as input.
This works from with in the same Sardana session, but as soon as I add this axis of my new pseudoCounter pseudoCounterAltOn which takes an IoverI0 pseudocounter as counter_role Sardana dies during startup.

Could anyone try to confirm that? pseudoCounter of a pseudoCounter?

**Comment by teresanunez** [comment]
The problem is if elements from the Pool depends one on the other ... if it is not created when the other one need it you get a error. You can only avoid it controlling the creation ... being sure that one is created one the other already exist ... So as you do when it work, start the Pool with only one and then create the other one.

**Comment by reszelaz** [comment]
First of all many thanks for sharing your solution! For sure this discussion will be usefull for others!
Actually after your initial question on the mailing list I didn't have time yet to look with more attention to your problem - it was on my TODO list.

Just a tiny comment about the `user_pre_acq` macro. I think that `getMotor` does not ensure the motor being stopped when you stop the macro. Better use `getMotion`. 

Now regarding the error that you report: `AttributeError: 'PoolPseudoCounter' object has no attribute 'log_obj'`. It looks to me like a bug. The `Logger` class is not initialized on time. I have checked how it is done in case of the `PoolPseudoMotor` and there the order of initialization of the base classes is exactly the opposite and was changed explicitly for the same need in 9435416. Hence I've tried to switch it for the `PoolPseudoCounter` as well (even if in the code I found a explicit comment: "don't switch the order of constructors!" I consider that this comment is outdated (it commes from ec15e55) with respect to the change for `PoolPseudoMotor` ). Could you please try this [code](https://github.com/reszelaz/sardana/tree/pc-early-log-init) and report back?

**Comment by reszelaz** [comment]
I think there are some more changes necessary, something like 6934be8. I will continue. For the moment don't try the code yet.

**Comment by dschick** [comment]
actually I have created the IoverI0 controller in the beginning and the newer one which takes the IoverI0 as input role.
Testing is a bit hard for me, since it crashes my whole setup and I need to delete the measurement group as well as the pseudoCounterController using Jive to get Sardana back running.
Accordingly, I need reconfigure the whole measurement group afterwards.

@reszelaz so this works also like 
`kepco = self.getMotion("kepco")`
?

**Comment by reszelaz** [comment]
> Testing is a bit hard for me, since it crashes my whole setup and I need to delete the measurement group as well as the pseudoCounterController using Jive to get Sardana back running.
Don't worry about the testing. Whenever I finish the implementation I will check a similar scenario. IoverI0 on top of another IoverI0.

Yes, the `getMotion` should be equivalent and provide you the automatic stop of the motor when you stop the macro.

**Comment by dschick** [comment]
I actually get an error when using `self.getMotion('kepco')` istead of` self.getMotor('kepco')`
is there an issue with the syntax?

**Comment by reszelaz** [comment]
`getMotion` expects a list as the argument (you can move more than one motor in the same motion operation). Hope this helps...

**Comment by dschick** [comment]
Thanks a lot. I'll try it next week.

reszelaz <notifications@github.com> schrieb am Mo., 16. Juli 2018, 17:50:
