### ISSUE TITLE
nexus recorder fails when an element is present twice in the snapshot group (SF#138)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#87]
If you add an element twice in the snapshot group (expconf allows you to do that), the scan execution fails due to problem with nexus recorder:

Traceback (most recent call last):
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py", line 1132, in runMacro
    for step in macro_obj.exec_():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macro.py", line 2150, in exec_
    for i in it:
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macros/scan.py", line 250, in run
    for step in self._gScan.step_scan():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 789, in step_scan
    self.start()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 745, in start
    self.data.start()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/scandata.py", line 259, in start
    self.datahandler.startRecordList(self)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 58, in startRecordList
    recorder.startRecordList(recordlist)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 116, in startRecordList
    self._startRecordList(recordlist)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/storage.py", line 794, in _startRecordList
    self._createPreScanSnapshot(env)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/storage.py", line 812, in _createPreScanSnapshot
    nid = self._writeData(label, pre_scan_value, dtype, shape=dd.shape or (1,)) #@todo: fallback shape is hardcoded!
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/storage.py", line 603, in _writeData
    self._makedata(name, dtype=dtype, shape=shape, chunks=chunks)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/storage.py", line 588, in _makedata
    self.fd.compmakedata(name, dtype=dtype, shape=shape, mode=mode, chunks=chunks)
  File "/homelocal/sicilia/lib/python/site-packages/nxs/napi.py", line 909, in compmakedata
    "Could not create compressed data %s: %s"%(name,self._loc())
ValueError: Could not create compressed data mot36: /home/zreszela/tmp/test.h5(/entry144/measurement/pre_scan_snapshot)

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/138](https://sourceforge.net/p/sardana/tickets/138)

**Comment by reszelaz** [comment]
`defsnap` is already preventing you to add the same element twice. `expconf` still does not and this could be improved.
Then, I think we will need to protect the `GScan._createPreScanSnapshot()` as well since it is possible to defien the snapshot directly via the environment variable.

**Comment by cpascual** [comment]
Together with @emiliojmorales , we tried to find a central place where we could sanitize the PreScanSnapshot info (removing duplicates). Unfortunately this info is passed using the `{g,s}etEnv` generic API instead of a specific one and therefore it is not easy to intercept calls setting the PreScanSnapshot info.

Therefore we fall back to handle the duplication in the nexus recorder and also to prevent setting duplicates in the expconf
