### ISSUE TITLE
Sardanaeditor does not work on windows

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#909]
This was observed in Jan18 and Jul18 release manual tests:

```
Door_demo2_1 [12]: !python C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py macrose
              ...: rver/demo2/1
MainThread     INFO     2018-08-09 08:16:32,140 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-08-09 08:16:34,437 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\Python27\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     WARNING  2018-08-09 08:16:46,778 TaurusRootLogger: C:\Python27\lib\site-packages\sardana\taurus\qt\qtgui\extra_sardana\macrotree.py:40: DeprecationWarning: taurus.qt.qtgui.resource is deprecated since 4.0. Use taurus.qt.qtgui.icon instead
  from taurus.qt.qtgui.resource import getIcon

Traceback (most recent call last):
  File "C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 595, in <module>
    main()
  File "C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 587, in main
    w = demo(args[0])
  File "C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 558, in demo
    test = SardanaEditor()
  File "C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 147, in __init__
    self.call__init__wo_kw(TaurusBaseEditor, parent)
  File "C:\Python27\lib\site-packages\taurus\core\util\object.py", line 60, in call__init__wo_kw
    klass.__init__(self, *args)
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\editor\tauruseditor.py", line 55, in __init__
    first=True)
  File "C:\Python27\lib\site-packages\spyder\widgets\editor.py", line 2419, in __init__
    self.register_editorstack_cb(self.editorstack)
  File "C:/Python27/lib/site-packages/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 208, in register_editorstack
    TaurusBaseEditor.register_editorstack(self, editorstack)
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\editor\tauruseditor.py", line 135, in register_editorstack
    editorstack.set_fullpath_sorting_enabled(True)
AttributeError: 'EditorStack' object has no attribute 'set_fullpath_sorting_enabled'
```

**Comment by reszelaz** [comment]
The same issue happens on CentOS 7 with spyder 3.3.0 (I guess) so it is platform independent.
It works well on debian 9 with the official package - version 3.1.3.

**Comment by daneos** [comment]
With Jul18 I used Spyder 3.3.0, but this issue was present also with 3.2.7 when testing Jan18 release.

**Comment by dschick** [comment]
hej, I am using spyder 3.3.1 and getting the same error with sardanaeditor

**Comment by reszelaz** [comment]
While testing Jul20 (3.0.2) release I found the following exception when starting sardanaeditor on Windows:

```
(py3qt5) C:\Users\IEUser>python -m sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor door_demo1_1
MainThread     INFO     2020-09-02 07:08:28,367 TaurusRootLogger: Using PyQt5 (v5.12.3 with Qt 5.12.5 and Python 3.7.8)
MainThread     INFO     2020-09-02 07:08:29,117 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\Miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     INFO     2020-09-02 07:08:29,195 TaurusRootLogger: Plugin "taurus_pyqtgraph" lazy-loaded as "taurus.qt.qtgui.tpg"
Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder
C:\Miniconda\envs\py3qt5\lib\runpy.py:125: RuntimeWarning: 'sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor' found in sys.modules after import of package 'sardana.taurus.qt.qtgui.extra_sardana', but prior to execution of 'sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
MainThread     WARNING  2020-09-02 07:08:38,086 TaurusRootLogger: <frozen importlib._bootstrap>:219: DeprecationWarning: taurus.core.util.argparse is deprecated since 4.5.4. Use argparse or (better) click instead

Traceback (most recent call last):
  File "C:\Miniconda\envs\py3qt5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Miniconda\envs\py3qt5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\sardana\taurus\qt\qtgui\extra_sardana\sardanaeditor.py", line 588, in <module>
    main()
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\sardana\taurus\qt\qtgui\extra_sardana\sardanaeditor.py", line 580, in main
    w = demo(args[0])
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\sardana\taurus\qt\qtgui\extra_sardana\sardanaeditor.py", line 550, in demo
    test = SardanaEditor()
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\sardana\taurus\qt\qtgui\extra_sardana\sardanaeditor.py", line 147, in __init__
    self.call__init__wo_kw(TaurusBaseEditor, parent)
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\taurus\core\util\object.py", line 62, in call__init__wo_kw
    klass.__init__(self, *args)
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\editor\tauruseditor.py", line 66, in __init__
    first=True)
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2956, in __init__
    self.editorstack = EditorStack(self, menu_actions)
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 469, in __init__
    self.__get_split_actions()
  File "C:\Miniconda\envs\py3qt5\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1570, in __get_split_actions
    if plugin._undocked_window is not None:
AttributeError: 'SardanaEditor' object has no attribute '_undocked_window'
```
