### ISSUE TITLE
showscan exception on startup

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#910]
This was revealed in Jul18 tests.

```
Door_demo2_1 [15]: showscan
Trying to open local scan file /tmp/demo2.h5...
Cannot plot scan:
Illegal slicing argument for scalar dataspace
```
Vagrant box: stretch64 v9.3
sardana dependencies install by:
```
$> apt-get install python-sardana
$> apt-get remove python-sardana python-taurus
```

Taurus 4.4 installed with pip
Sardana 2.5 istalled from the release artifact.

**Comment by teresanunez** [comment]
I confirm this using debian9 with taurus 4.4 and sardana releaseJul18 installed using setup.py file.

**Comment by reszelaz** [comment]
The widget seems funtional. One can select channels and they are plotted.
There are however errors messages printed on spock:
```
Door_zreszela_1 [9]: showscan
/usr/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Trying to open local scan file /tmp/test-showscan.h5...
Cannot plot scan:
Illegal slicing argument for scalar dataspace

Door_zreszela_1 [10]: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableView.py", line 44, in columnCount
    return self.parent().columnCount()
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableModel.py", line 52, in columnCount
    return self._columnCount(parent)
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableModel.py", line 104, in _columnCount3DIndex0
    return self._array.shape[2]
IndexError: tuple index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableView.py", line 44, in columnCount
    return self.parent().columnCount()
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableModel.py", line 52, in columnCount
    return self._columnCount(parent)
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/misc/NumpyArrayTableModel.py", line 104, in _columnCount3DIndex0
    return self._array.shape[2]
IndexError: tuple index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
```

**Comment by reszelaz** [comment]
While testing Jul20 release (3.0.2) on Windows, with PyMca 5.5.5 we get the following exception:

```
Door_demo1_1 [1]: showscan
MainThread     INFO     2020-08-27 03:03:36,612 PyMca5.PyMcaGui.PyMcaQt: BINDING set to PyQt5
Trying to open local scan file C:/Users/IEUser/tmp\demo1.h5...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\miniconda\envs\py3qt5\lib\site-packages\PyMca5\PyMcaGui\io\hdf5\HDF5Widget.py in selectionChanged(self, selected, deselected)
    702         event = "itemSelectionChanged"
    703         modelIndex = self.currentIndex()
--> 704         self.emitSignal(event, modelIndex)
    705
    706     def emitSignal(self, event, modelIndex):

c:\miniconda\envs\py3qt5\lib\site-packages\PyMca5\PyMcaGui\io\hdf5\HDF5Widget.py in emitSignal(self, event, modelIndex)
    721         ddict['shape'] = item.shape
    722         ddict['color'] = item.color
--> 723         ddict['mouse'] = self._lastMouse * 1
    724         self.sigHDF5WidgetSignal.emit(ddict)
    725

AttributeError: 'HDF5Widget' object has no attribute '_lastMouse'
Cannot plot scan:
Illegal slicing argument for scalar dataspace
```
However the widget is functional.

**Comment by reszelaz** [comment]
Still there on Jan21 release tests.
