### ISSUE TITLE
spock warning

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#916]
again after the recent upgrade to Sardana 2.5 I get this warning in spock:

```
[TerminalIPythonApp] WARNING | Error in loading extension: sardana.spock
Check your config files in /home/moke/.ipython/profile_spockdoor
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/shellapp.py", line 248, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 85, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/home/moke/Repos/sardana/src/sardana/spock/ipython_01_00/genutils.py", line 968, in load_ipython_extension
    macro_server = get_macro_server()
  File "/home/moke/Repos/sardana/src/sardana/spock/ipython_01_00/genutils.py", line 642, in get_macro_server
    return _get_dev('macro_server')
  File "/home/moke/Repos/sardana/src/sardana/spock/ipython_01_00/genutils.py", line 622, in _get_dev
    if not dev_name.startswith("tango://"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by teresanunez** [comment]
Hi @dschick, only to clarify ... do you have then Sardana running?, if not you can not connect to the door with spock.

**Comment by dschick** [comment]
okay, so sardana is running but with the problems reported in #915 
So I will check, if the warning disappears when #915 is solved, but from the warning message I thought it might not be connected to that.

**Comment by teresanunez** [comment]
May be it is not related, but it is better to have everything running correctly first, and then we will see.

**Comment by teresanunez** [comment]
@dschick, which Taurus version do you have?

**Comment by teresanunez** [comment]
@dschick, please check creating a new profile:

./spock --profile=mytest

**Comment by dschick** [comment]
hej @teresanunez , the warning disappears when the pool is running.
I will close the issue, thanks for the quick help

**Comment by teresanunez** [comment]
Perfect !
