### ISSUE TITLE
Interactive macros (iMacro) have error when using Qt version 4.4 (SF#149)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#94]
We have detected an error with interactive macros when using Qt 4.4.3 (this error does not exist with Qt version 4.7.4: interactive macros works well with Qt 4.7.4).

The error comes from the function setStrecth from QHBoxLayout. This function was introduced in Qt4.5.

It seems that the error is coming from horizontalLayout API. In machines where we are using Qt 4.4.3 (the suse11 machines) we get the following error when trying to execute and interactive macro:

Door_mrosanes_1 [5]: %ask_for_car_brand
Traceback (most recent call last):
  File "/homelocal/sicilia/lib/python/site-packages/sardana/spock/inputhandler.py", line 84, in on_message
    self._dialog = dialog = TaurusInputDialog(input_data=input_data)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/qt/qtgui/dialog/taurusinputdialog.py", line 134, in __init__
    self._panel = panel = input_panel_klass(input_data, self)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/qt/qtgui/panel/taurusinputpanel.py", line 100, in __init__
    _ui.setupUi(self)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/qt/qtgui/panel/ui/ui_TaurusInputPanel.py", line 35, in setupUi
    self.horizontalLayout.setStretch(0, 1)
AttributeError: setStretch

If it is possible it  would be nice to include the fix for the following Sardana realease.
Thanks in advance.

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/149](https://sourceforge.net/p/sardana/tickets/149)

**Comment by reszelaz** [comment]
We do not support Qt 4.4 anymore. The issue is not present when using neither of:
* PyQt4 (v4.11.4 with Qt 4.8.7 and Python 3.5.3
* PyQt5 (v5.7 with Qt 5.7.1 and Python 3.5.3)
So I'm closing as won't fix.
