### ISSUE TITLE
conda environment, pyqt5, Taurus keeps on using pyqt4

### ISSUE THREAD

**Issue by mguijarr** [sardana-org/sardana#970]
Hi,

I created a Conda environment to install sardana:

    conda create -n sardana python=2

Then, I installed PyTango using ESRF BCU channel:

    conda install pytango -c esrf-bcu

Then, I installed Sardana with pip:

    pip install sardana

I tried to run `spock`, I got the error message about missing Qt. So I installed latest PyQt:

    conda install pyqt

PyQt5 got installed, I tested that import works ok but still Spock was reporting the following
exception traceback:

```
      File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 85, in <module>
    from taurus.external.qt import Qt
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/external/qt/__init__.py", line 133, in <module>
    raise PythonQtError('No Qt bindings could be found')
```

So I looked a bit in the code and added `QT_API=pyqt5` as an environment variable.

The next error message when starting Spock is:

```
MainThread     INFO     2018-10-24 09:13:14,403 TaurusRootLogger: Using "PyQt5" for Qt
/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated since IPython 4.0. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "/home/matias/miniconda2/envs/sardana/bin/spock", line 7, in <module>
    from sardana.spock import main
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/__init__.py", line 34, in main
    run()
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 1357, in run
    prepare_input_handler()
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 1258, in prepare_input_handler
    import sardana.spock.inputhandler
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/inputhandler.py", line 38, in <module>
    from taurus.qt.qtgui.dialog import TaurusMessageBox, TaurusInputDialog
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/__init__.py", line 35, in <module>
    import icon as __icon
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/icon/__init__.py", line 32, in <module>
    from catalog import QIconCatalog
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/icon/catalog.py", line 31, in <module>
    from taurus.qt.qtgui.input import GraphicalChoiceWidget
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/input/__init__.py", line 32, in <module>
    from .tauruscheckbox import *
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/input/tauruscheckbox.py", line 33, in <module>
    from taurus.qt.qtgui.base import TaurusBaseWritableWidget
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/base/__init__.py", line 31, in <module>
    from .taurusbase import *
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/base/taurusbase.py", line 54, in <module>
    from taurus.qt.qtcore.util.signal import baseSignal
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtcore/util/signal.py", line 5, in <module>
    from PyQt4 import Qt
ImportError: No module named PyQt4
```

So, it seems Taurus does not work with PyQt5 somehow.

Finally I downgraded PyQt to PyQt 4. I had to set QT_API to "pyqt" explicitely, otherwise I got the
following error:

```
Traceback (most recent call last):
  File "/home/matias/miniconda2/envs/sardana/bin/spock", line 7, in <module>
    from sardana.spock import main
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/__init__.py", line 29, in <module>
    from genutils import load_ipython_extension, unload_ipython_extension, \
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/genutils.py", line 73, in <module>
    from ipython_01_00.genutils import *
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 85, in <module>
    from taurus.external.qt import Qt
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/external/qt/__init__.py", line 80, in <module>
    assert API in (PYQT5_API + PYQT4_API + PYSIDE_API)
AssertionError
```

Finally I had to install `qtpy`:
    
    conda install qtpy

And I could start.

**Comment by cpascual** [comment]
Hi @mguijarr , even if the Taurus source code has refs to Qt5, this is not yet supported.
In fact we are right now working on that: see https://github.com/taurus-org/taurus/pull/814

So, until Qt5 is supported (hopefully in the next release in January 2019), you need to use pyqt4 just as you already found out.
