### ISSUE TITLE
Missing profile_spockdoor/ipython_profile.py

### ISSUE THREAD

**Issue by mguijarr** [sardana-org/sardana#971]
When starting spock for the first time, if the Sardana server is not running, it asks to create a
spock profile then it asks for a Door to use. At this moment, if the process is interrupted (because
the guy thinks "Oh it's true I have to run Sardana server first ! Let's start it and I will try again")
spock cannot restart:

```
MainThread     INFO     2018-10-24 09:45:23,371 TaurusRootLogger: Using "PyQt4" for Qt
/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/qtpy/__init__.py:211: RuntimeWarning: Selected binding "pyqt" could not be found, using "pyqt4"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated since IPython 4.0. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
MainThread     INFO     2018-10-24 09:45:23,401 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/home/matias/miniconda2/envs/sardana/bin/spock", line 11, in <module>
    sys.exit(main())
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/__init__.py", line 34, in main
    run()
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 1358, in run
    prepare_cmdline()
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 1306, in prepare_cmdline
    check_for_upgrade(ipy_profile_dir)
  File "/home/matias/miniconda2/envs/sardana/lib/python2.7/site-packages/sardana/spock/ipython_01_00/genutils.py", line 820, in check_for_upgrade
    with file(abs_config_file_name, "r") as ipy_config_file:
IOError: [Errno 2] No such file or directory: u'/home/matias/.ipython/profile_spockdoor/ipython_config.py'
```

Removing ~/.ipython/` directory solves the problem.

**Comment by reszelaz** [comment]
Thanks @mguijarr for the report. I tried to fix it in #973.
