### ISSUE TITLE
NXscanH5_FileRecorder does not work if 1D channel Max Dim X != Dim X

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#985]
One can reproduce it with a dummy 1D experimental channel commenting `GetAxisAttributes` method in the `DummyOneDController` controller. This method optimizes the Max Dim X and adjust it to 1024. The default Max Dim X for a 1D experimental channel is 16384.

This is the error that we get:

```
Door_zreszela_1 [42]: ascan mot01 0 1 1 0.001
Operation will be saved in /home/zreszela/tmp/test.h5 (HDF5::NXscan)
Operation will be saved in /home/zreszela/tmp/test.dat (Spec)
Scan #1919 started at Mon Nov 19 18:55:43 2018. It will take at least 0:00:00.128491
 #Pt No    mot01     oned01      dt   
   0         0      (1024,)   0.107483
   0         0      (1024,)   0.107483
An error occurred while running Macro 'ascan(mot01, 0.0, 1.0, 1, 0.001) -> 556f284a-ec24-11e8-8fa5-f8b156a48f79':
Can't broadcast (1024,) -> (1, 16384)

Door_zreszela_1 [43]: www
Traceback (most recent call last):
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py", line 1561, in runMacro
    for step in macro_obj.exec_():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macro.py", line 2318, in exec_
    for i in it:
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macros/scan.py", line 291, in run
    for step in self._gScan.step_scan():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 965, in step_scan
    self.end()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 919, in end
    self.data.end()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/scandata.py", line 500, in end
    self.datahandler.addRecord(self, rc)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 68, in addRecord
    recorder.writeRecord(record)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 142, in writeRecord
    self._writeRecord(record)
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/recorders/h5storage.py", line 303, in _writeRecord
    _ds[record.recordno, ...] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2842)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2800)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 629, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
TypeError: Can't broadcast (1024,) -> (1, 16384)
```

**Comment by mrosanes** [comment]
Could not reproduce the error (tested with h5py 2.7.1 and then with the system installed h5py 2.7.0).

The traceback is strange as in `self.data.end()` it executes `self.datahandler.addRecord(self, rc)`; and this should only happen in continuous scans, to do the final padding of records; and not in step scans.

We close the ticket, as it cannot be reproduced.
